var dir_8c8ca33bd0f68a908c3dfb3e1a9becc3 =
[
    [ "cleanEntries.cc", "d3/dc0/cleanEntries_8cc.html", "d3/dc0/cleanEntries_8cc" ],
    [ "cleanEntries.hpp", "da/dd1/cleanEntries_8hpp_source.html", null ],
    [ "copyright.cc", "d0/d76/copyright_8cc.html", "d0/d76/copyright_8cc" ],
    [ "copyright.hpp", "d2/d05/copyright_8hpp_source.html", null ],
    [ "copyrightState.cc", "df/dff/copyrightState_8cc_source.html", null ],
    [ "copyrightState.hpp", "df/d6f/copyrightState_8hpp_source.html", null ],
    [ "copyrightUtils.cc", "da/de3/copyrightUtils_8cc.html", "da/de3/copyrightUtils_8cc" ],
    [ "copyrightUtils.hpp", "de/d6c/copyrightUtils_8hpp_source.html", null ],
    [ "copyscan.cc", "da/df2/copyscan_8cc_source.html", null ],
    [ "copyscan.hpp", "d8/d72/copyscan_8hpp_source.html", null ],
    [ "database.cc", "d3/d66/database_8cc_source.html", null ],
    [ "database.hpp", "df/da2/database_8hpp_source.html", null ],
    [ "directoryScan.cc", "d6/d9b/copyright_2agent_2directoryScan_8cc.html", "d6/d9b/copyright_2agent_2directoryScan_8cc" ],
    [ "directoryScan.hpp", "d0/d26/copyright_2agent_2directoryScan_8hpp_source.html", null ],
    [ "FossologyUnicodeClean.cc", "da/d22/FossologyUnicodeClean_8cc_source.html", null ],
    [ "FossologyUnicodeClean.hpp", "d6/d1a/FossologyUnicodeClean_8hpp.html", "d6/d1a/FossologyUnicodeClean_8hpp" ],
    [ "identity.hpp", "d7/d0e/identity_8hpp_source.html", null ],
    [ "regex.hpp", "d6/d6f/regex_8hpp_source.html", null ],
    [ "regexConfParser.cc", "d0/da5/regexConfParser_8cc.html", "d0/da5/regexConfParser_8cc" ],
    [ "regexConfParser.hpp", "d8/df6/regexConfParser_8hpp_source.html", null ],
    [ "regexConfProvider.cc", "d0/d67/regexConfProvider_8cc.html", "d0/d67/regexConfProvider_8cc" ],
    [ "regexConfProvider.hpp", "d6/d3f/regexConfProvider_8hpp_source.html", null ],
    [ "regscan.cc", "d4/d74/regscan_8cc_source.html", null ],
    [ "regscan.hpp", "d0/d8c/regscan_8hpp_source.html", null ],
    [ "scanners.cc", "dd/d98/scanners_8cc_source.html", null ],
    [ "scanners.hpp", "d9/db0/scanners_8hpp.html", "d9/db0/scanners_8hpp" ]
];