var hierarchy =
[
    [ "Fossology\\UI\\Api\\Models\\AdminAcknowledgement", "d9/d2d/classFossology_1_1UI_1_1Api_1_1Models_1_1AdminAcknowledgement.html", null ],
    [ "Fossology\\Lib\\Agent\\Agent", "da/d74/classFossology_1_1Lib_1_1Agent_1_1Agent.html", [
      [ "DecisionExporter", "d0/df2/classDecisionExporter.html", null ],
      [ "Fossology\\CliXml\\CliXml", "d6/d4a/classFossology_1_1CliXml_1_1CliXml.html", null ],
      [ "Fossology\\CycloneDX\\CycloneDXAgent", "d7/dea/classFossology_1_1CycloneDX_1_1CycloneDXAgent.html", null ],
      [ "Fossology\\Decider\\DeciderAgent", "d7/d6c/classFossology_1_1Decider_1_1DeciderAgent.html", null ],
      [ "Fossology\\DeciderJob\\DeciderJobAgent", "da/df8/classFossology_1_1DeciderJob_1_1DeciderJobAgent.html", null ],
      [ "Fossology\\DecisionImporter\\DecisionImporterAgent", "de/d05/classFossology_1_1DecisionImporter_1_1DecisionImporterAgent.html", null ],
      [ "Fossology\\ReportImport\\ReportImportAgent", "db/dde/classFossology_1_1ReportImport_1_1ReportImportAgent.html", null ],
      [ "Fossology\\Reso\\ResoAgent", "d1/d66/classFossology_1_1Reso_1_1ResoAgent.html", null ],
      [ "Fossology\\Reuser\\ReuserAgent", "d4/d03/classFossology_1_1Reuser_1_1ReuserAgent.html", null ],
      [ "Fossology\\SoftwareHeritage\\softwareHeritageAgent", "d4/d89/classFossology_1_1SoftwareHeritage_1_1softwareHeritageAgent.html", null ],
      [ "Fossology\\Spasht\\SpashtAgent", "db/d7b/classFossology_1_1Spasht_1_1SpashtAgent.html", null ],
      [ "Fossology\\Spdx\\SpdxAgent", "d5/dc2/classFossology_1_1Spdx_1_1SpdxAgent.html", null ],
      [ "ReadmeOssAgent", "d7/d57/classReadmeOssAgent.html", null ],
      [ "UnifiedReport", "d1/d15/classUnifiedReport.html", null ]
    ] ],
    [ "Fossology\\UI\\Api\\Models\\Agent", "d7/dcf/classFossology_1_1UI_1_1Api_1_1Models_1_1Agent.html", null ],
    [ "agent_info", "dc/d46/structagent__info.html", null ],
    [ "agent_spawn_args", "d0/d98/structagent__spawn__args.html", null ],
    [ "agent_t", "df/d1d/structagent__t.html", null ],
    [ "Fossology\\Lib\\Dao\\AgentDao", "d5/d42/classFossology_1_1Lib_1_1Dao_1_1AgentDao.html", null ],
    [ "fo::AgentDatabaseHandler", "de/d65/classfo_1_1AgentDatabaseHandler.html", [
      [ "CompatibilityDatabaseHandler", "db/d68/classCompatibilityDatabaseHandler.html", null ],
      [ "CopyrightDatabaseHandler", "d2/d40/classCopyrightDatabaseHandler.html", null ],
      [ "NinkaDatabaseHandler", "d7/dd8/classNinkaDatabaseHandler.html", null ],
      [ "OjosDatabaseHandler", "d3/df9/classOjosDatabaseHandler.html", null ],
      [ "ScancodeDatabaseHandler", "d0/dec/classScancodeDatabaseHandler.html", null ]
    ] ],
    [ "Fossology\\Lib\\BusinessRules\\AgentLicenseEventProcessor", "dc/d37/classFossology_1_1Lib_1_1BusinessRules_1_1AgentLicenseEventProcessor.html", null ],
    [ "Fossology\\Lib\\Data\\AgentRef", "da/daa/classFossology_1_1Lib_1_1Data_1_1AgentRef.html", null ],
    [ "ajax_upload_agents", "dc/dff/classajax__upload__agents.html", null ],
    [ "Fossology\\Lib\\Dao\\AllDecisionsDao", "da/d36/classFossology_1_1Lib_1_1Dao_1_1AllDecisionsDao.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Analysis", "d4/d6c/classFossology_1_1UI_1_1Api_1_1Models_1_1Analysis.html", null ],
    [ "FoScanner.ApiConfig.ApiConfig", "d5/d9e/classFoScanner_1_1ApiConfig_1_1ApiConfig.html", null ],
    [ "Fossology\\UI\\Api\\Models\\ApiVersion", "dc/d25/classFossology_1_1UI_1_1Api_1_1Models_1_1ApiVersion.html", null ],
    [ "arg_int", "d6/d9b/structarg__int.html", null ],
    [ "Fossology\\Lib\\Util\\ArrayOperation", "d8/dcf/classFossology_1_1Lib_1_1Util_1_1ArrayOperation.html", null ],
    [ "CPPUNIT_NS::assertion_traits< LicenseMatch >", "dc/dab/structCPPUNIT__NS_1_1assertion__traits_3_01LicenseMatch_01_4.html", null ],
    [ "Fossology\\Lib\\Auth\\Auth", "d9/d99/classFossology_1_1Lib_1_1Auth_1_1Auth.html", null ],
    [ "Fossology\\UI\\Api\\Helper\\AuthHelper", "d4/d85/classFossology_1_1UI_1_1Api_1_1Helper_1_1AuthHelper.html", null ],
    [ "Fossology\\CycloneDX\\BomReportGenerator", "db/d1b/classFossology_1_1CycloneDX_1_1BomReportGenerator.html", null ],
    [ "bucketdef_struct", "d7/dde/structbucketdef__struct.html", null ],
    [ "bucketpool_struct", "d1/d4c/structbucketpool__struct.html", null ],
    [ "BulkAction", "d8/d79/structBulkAction.html", null ],
    [ "BulkArguments", "d7/d39/structBulkArguments.html", null ],
    [ "Fossology\\UI\\Api\\Models\\BulkHistory", "d8/d81/classFossology_1_1UI_1_1Api_1_1Models_1_1BulkHistory.html", null ],
    [ "Fossology\\Decider\\BulkReuser", "d0/db5/classFossology_1_1Decider_1_1BulkReuser.html", null ],
    [ "cachenode", "d2/d35/structcachenode.html", null ],
    [ "cacheroot", "d4/d04/structcacheroot.html", null ],
    [ "check4jobs", "da/dcc/classcheck4jobs.html", null ],
    [ "Cksum", "db/d75/structCksum.html", null ],
    [ "CksumFile", "d9/d84/structCksumFile.html", null ],
    [ "Fossology\\Lib\\Test\\ClassWithPrivateMethod", "da/d0f/classFossology_1_1Lib_1_1Test_1_1ClassWithPrivateMethod.html", null ],
    [ "Fossology\\Lib\\Report\\ClearedGetterCommon", "d1/da4/classFossology_1_1Lib_1_1Report_1_1ClearedGetterCommon.html", [
      [ "Fossology\\Lib\\Report\\BulkMatchesGetter", "d3/d64/classFossology_1_1Lib_1_1Report_1_1BulkMatchesGetter.html", null ],
      [ "Fossology\\Lib\\Report\\LicenseClearedGetter", "d6/d7f/classFossology_1_1Lib_1_1Report_1_1LicenseClearedGetter.html", null ],
      [ "Fossology\\Lib\\Report\\LicenseDNUGetter", "d1/dd6/classFossology_1_1Lib_1_1Report_1_1LicenseDNUGetter.html", null ],
      [ "Fossology\\Lib\\Report\\LicenseIrrelevantGetter", "d6/d71/classFossology_1_1Lib_1_1Report_1_1LicenseIrrelevantGetter.html", null ],
      [ "Fossology\\Lib\\Report\\LicenseMainGetter", "d3/db1/classFossology_1_1Lib_1_1Report_1_1LicenseMainGetter.html", null ],
      [ "Fossology\\Lib\\Report\\LicenseNonFunctionalGetter", "d5/d60/classFossology_1_1Lib_1_1Report_1_1LicenseNonFunctionalGetter.html", null ],
      [ "Fossology\\Lib\\Report\\TestClearedGetter", "d2/deb/classFossology_1_1Lib_1_1Report_1_1TestClearedGetter.html", null ],
      [ "Fossology\\Lib\\Report\\WeirdCharClearedGetter", "db/d37/classFossology_1_1Lib_1_1Report_1_1WeirdCharClearedGetter.html", null ],
      [ "Fossology\\Lib\\Report\\XpClearedGetter", "d4/d21/classFossology_1_1Lib_1_1Report_1_1XpClearedGetter.html", null ]
    ] ],
    [ "Fossology\\Lib\\Dao\\ClearingDao", "d1/d9f/classFossology_1_1Lib_1_1Dao_1_1ClearingDao.html", null ],
    [ "Fossology\\Lib\\Data\\ClearingDecision", "d3/dcf/classFossology_1_1Lib_1_1Data_1_1ClearingDecision.html", null ],
    [ "Fossology\\Lib\\Data\\ClearingDecisionBuilder", "d7/d04/classFossology_1_1Lib_1_1Data_1_1ClearingDecisionBuilder.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\ClearingDecisionFilter", "d7/dc9/classFossology_1_1Lib_1_1BusinessRules_1_1ClearingDecisionFilter.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\ClearingDecisionProcessor", "d3/da0/classFossology_1_1Lib_1_1BusinessRules_1_1ClearingDecisionProcessor.html", null ],
    [ "Fossology\\Lib\\Data\\Clearing\\ClearingEventBuilder", "dc/d96/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingEventBuilder.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\ClearingEventProcessor", "dc/d8e/classFossology_1_1Lib_1_1BusinessRules_1_1ClearingEventProcessor.html", null ],
    [ "Fossology\\UI\\Api\\Models\\ClearingHistory", "d8/df2/classFossology_1_1UI_1_1Api_1_1Models_1_1ClearingHistory.html", null ],
    [ "Fossology\\Lib\\Data\\Clearing\\ClearingLicense", "d4/df0/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingLicense.html", null ],
    [ "CliOptions", "d5/d1b/classCliOptions.html", null ],
    [ "cmdlist", "d4/d71/structcmdlist.html", null ],
    [ "CopyrightDatabaseHandler::ColumnDef", "d6/d05/structCopyrightDatabaseHandler_1_1ColumnDef.html", null ],
    [ "ScancodeDatabaseHandler::ColumnDef", "d9/d5b/structScancodeDatabaseHandler_1_1ColumnDef.html", null ],
    [ "CompatibilityAgent", "da/d2e/classCompatibilityAgent.html", null ],
    [ "CompatibilityCliOptions", "d3/dec/classCompatibilityCliOptions.html", null ],
    [ "Fossology\\Lib\\Dao\\CompatibilityDao", "d2/d8e/classFossology_1_1Lib_1_1Dao_1_1CompatibilityDao.html", null ],
    [ "CompatibilityDatabaseEntry", "d1/ddc/structCompatibilityDatabaseEntry.html", null ],
    [ "CompatibilityState", "d0/d40/classCompatibilityState.html", null ],
    [ "Fossology\\Lib\\Data\\Package\\ComponentType", "db/d09/classFossology_1_1Lib_1_1Data_1_1Package_1_1ComponentType.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Conf", "d8/d04/classFossology_1_1UI_1_1Api_1_1Models_1_1Conf.html", null ],
    [ "ConfigSys", "d3/df7/classConfigSys.html", null ],
    [ "ContainerInfo", "d8/db7/structContainerInfo.html", null ],
    [ "Fossology\\Lib\\Text\\Converter", "d7/d62/interfaceFossology_1_1Lib_1_1Text_1_1Converter.html", [
      [ "Fossology\\Lib\\Text\\EncodingConverter", "dd/d30/classFossology_1_1Lib_1_1Text_1_1EncodingConverter.html", null ]
    ] ],
    [ "Fossology\\Lib\\Data\\Spasht\\Coordinate", "d1/d9f/classFossology_1_1Lib_1_1Data_1_1Spasht_1_1Coordinate.html", null ],
    [ "Fossology\\Lib\\Dao\\CopyrightDao", "d6/df7/classFossology_1_1Lib_1_1Dao_1_1CopyrightDao.html", null ],
    [ "Fossology\\Lib\\Util\\CopyrightLister", "d5/d8d/classFossology_1_1Lib_1_1Util_1_1CopyrightLister.html", null ],
    [ "CopyrightScheduledTest", "df/ddb/classCopyrightScheduledTest.html", null ],
    [ "CopyrightState", "d1/df2/classCopyrightState.html", null ],
    [ "Fossology\\UI\\Api\\Helper\\CorsHelper", "db/dd9/classFossology_1_1UI_1_1Api_1_1Helper_1_1CorsHelper.html", null ],
    [ "Fossology\\Lib\\Application\\CurlRequest", "db/de4/classFossology_1_1Lib_1_1Application_1_1CurlRequest.html", null ],
    [ "Fossology\\Lib\\Application\\CurlRequestService", "d1/d25/classFossology_1_1Lib_1_1Application_1_1CurlRequestService.html", null ],
    [ "curScan", "d9/dc4/structcurScan.html", null ],
    [ "cyclonedxAgent", "d0/d7f/classcyclonedxAgent.html", null ],
    [ "DatabaseEntry", "d1/d60/classDatabaseEntry.html", null ],
    [ "Fossology\\Lib\\Util\\DataTablesUtility", "d5/d4d/classFossology_1_1Lib_1_1Util_1_1DataTablesUtility.html", null ],
    [ "db", "de/d5f/classdb.html", null ],
    [ "Fossology\\UI\\Api\\Helper\\DbHelper", "d8/d61/classFossology_1_1UI_1_1Api_1_1Helper_1_1DbHelper.html", null ],
    [ "fo::DbManager", "d3/d64/classfo_1_1DbManager.html", null ],
    [ "Fossology\\Lib\\Db\\DbManager", "de/dcb/classFossology_1_1Lib_1_1Db_1_1DbManager.html", [
      [ "Fossology\\Lib\\Db\\ModernDbManager", "de/da5/classFossology_1_1Lib_1_1Db_1_1ModernDbManager.html", null ],
      [ "Fossology\\Lib\\Db\\SolidDbManager", "db/d8d/classFossology_1_1Lib_1_1Db_1_1SolidDbManager.html", null ]
    ] ],
    [ "fo::DbManagerStructDeleter", "dd/df3/classfo_1_1DbManagerStructDeleter.html", null ],
    [ "Fossology\\Lib\\Proxy\\DbViewProxy", "d3/dae/classFossology_1_1Lib_1_1Proxy_1_1DbViewProxy.html", [
      [ "Fossology\\Lib\\Proxy\\LatestScannerProxy", "dc/d54/classFossology_1_1Lib_1_1Proxy_1_1LatestScannerProxy.html", null ],
      [ "Fossology\\Lib\\Proxy\\LicenseViewProxy", "d0/da6/classFossology_1_1Lib_1_1Proxy_1_1LicenseViewProxy.html", null ],
      [ "Fossology\\Lib\\Proxy\\UploadTreeProxy", "d6/dd3/classFossology_1_1Lib_1_1Proxy_1_1UploadTreeProxy.html", null ],
      [ "Fossology\\Lib\\Proxy\\UploadTreeViewProxy", "d2/d77/classFossology_1_1Lib_1_1Proxy_1_1UploadTreeViewProxy.html", null ]
    ] ],
    [ "debpkginfo", "d0/d5f/structdebpkginfo.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Decider", "d2/d5d/classFossology_1_1UI_1_1Api_1_1Models_1_1Decider.html", null ],
    [ "Fossology\\DecisionImporter\\DecisionImporterDataCreator", "db/d1d/classFossology_1_1DecisionImporter_1_1DecisionImporterDataCreator.html", null ],
    [ "Fossology\\DecisionImporter\\DecisionImporterIdFetcher", "d8/d5b/classFossology_1_1DecisionImporter_1_1DecisionImporterIdFetcher.html", null ],
    [ "Fossology\\Lib\\Data\\Spasht\\DefinitionSummary", "dd/d42/classFossology_1_1Lib_1_1Data_1_1Spasht_1_1DefinitionSummary.html", null ],
    [ "Fossology\\DelAgent\\UI\\DeleteMessages", "da/d26/classFossology_1_1DelAgent_1_1UI_1_1DeleteMessages.html", null ],
    [ "Fossology\\DelAgent\\UI\\DeleteResponse", "db/dfa/classFossology_1_1DelAgent_1_1UI_1_1DeleteResponse.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\DetectLicensesFolder", "d3/dd2/classFossology_1_1Lib_1_1BusinessRules_1_1DetectLicensesFolder.html", null ],
    [ "DiffMatchInfo", "df/dbf/structDiffMatchInfo.html", null ],
    [ "DiffPoint", "dd/d6b/structDiffPoint.html", null ],
    [ "DiffResult", "dd/d45/structDiffResult.html", null ],
    [ "dirlist", "df/d8d/structdirlist.html", null ],
    [ "domParseLicenseTbl", "d9/d38/classdomParseLicenseTbl.html", null ],
    [ "ScanDeps.Downloader.Downloader", "da/d41/classScanDeps_1_1Downloader_1_1Downloader.html", null ],
    [ "Fossology\\Lib\\Util\\DownloadUtil", "d4/d38/classFossology_1_1Lib_1_1Util_1_1DownloadUtil.html", null ],
    [ "Fossology\\Lib\\Db\\Driver", "dc/d26/interfaceFossology_1_1Lib_1_1Db_1_1Driver.html", [
      [ "Fossology\\Lib\\Db\\Driver\\Postgres", "d9/d71/classFossology_1_1Lib_1_1Db_1_1Driver_1_1Postgres.html", null ],
      [ "Fossology\\Lib\\Db\\Driver\\SqliteE", "d9/d03/classFossology_1_1Lib_1_1Db_1_1Driver_1_1SqliteE.html", null ]
    ] ],
    [ "Fossology\\UI\\Api\\Models\\EditedLicense", "d6/d3d/classFossology_1_1UI_1_1Api_1_1Models_1_1EditedLicense.html", null ],
    [ "email_replace_args", "d5/d17/structemail__replace__args.html", null ],
    [ "event_loop", "d9/de5/structevent__loop.html", null ],
    [ "event_t", "da/d67/structevent__t.html", null ],
    [ "exportLicenseRef", "d9/d97/classexportLicenseRef.html", null ],
    [ "Fossology\\Lib\\Agent\\FgetsMock", "dd/dda/classFossology_1_1Lib_1_1Agent_1_1FgetsMock.html", null ],
    [ "File", "d6/d88/structFile.html", null ],
    [ "fo::File", "db/df3/classfo_1_1File.html", null ],
    [ "Fossology\\UI\\Api\\Models\\File", "dd/d7a/classFossology_1_1UI_1_1Api_1_1Models_1_1File.html", null ],
    [ "Fossology\\UI\\Api\\Helper\\FileHelper", "d3/d56/classFossology_1_1UI_1_1Api_1_1Helper_1_1FileHelper.html", null ],
    [ "Fossology\\UI\\Api\\Models\\FileInfo", "d2/d35/classFossology_1_1UI_1_1Api_1_1Models_1_1FileInfo.html", null ],
    [ "Fossology\\UI\\Api\\Models\\FileLicenses", "d8/dd7/classFossology_1_1UI_1_1Api_1_1Models_1_1FileLicenses.html", null ],
    [ "Fossology\\Lib\\Data\\Report\\FileNode", "dc/dbc/classFossology_1_1Lib_1_1Data_1_1Report_1_1FileNode.html", null ],
    [ "FileResult_struct", "d3/d9f/structFileResult__struct.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Findings", "d3/d6b/classFossology_1_1UI_1_1Api_1_1Models_1_1Findings.html", null ],
    [ "fo_conf", "d8/d1b/structfo__conf.html", null ],
    [ "fo_dbmanager", "dd/d3c/structfo__dbmanager.html", null ],
    [ "fo_dbManager", "d0/de7/structfo__dbManager.html", null ],
    [ "fo_dbmanager_preparedstatement", "d1/ddd/structfo__dbmanager__preparedstatement.html", null ],
    [ "fo_dbManager_PreparedStatement", "d9/d2a/structfo__dbManager__PreparedStatement.html", null ],
    [ "fo_libschema", "d3/d69/classfo__libschema.html", null ],
    [ "Fossology\\DecisionImporter\\FoDecisionData", "d2/d67/classFossology_1_1DecisionImporter_1_1FoDecisionData.html", null ],
    [ "FoDecisionExporter", "d5/df3/classFoDecisionExporter.html", null ],
    [ "FoIntegration", "d6/d13/classFoIntegration.html", [
      [ "Build", "d2/de0/classBuild.html", null ]
    ] ],
    [ "Fossology\\Lib\\Data\\Folder\\Folder", "de/d1c/classFossology_1_1Lib_1_1Data_1_1Folder_1_1Folder.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Folder", "df/d7d/classFossology_1_1UI_1_1Api_1_1Models_1_1Folder.html", null ],
    [ "Fossology\\Lib\\Dao\\FolderDao", "d4/d11/classFossology_1_1Lib_1_1Dao_1_1FolderDao.html", null ],
    [ "Fossology\\Lib\\UI\\FolderNav", "d0/d3d/classFossology_1_1Lib_1_1UI_1_1FolderNav.html", null ],
    [ "FoScanner.FormatResults.FormatResult", "de/d1b/classFoScanner_1_1FormatResults_1_1FormatResult.html", null ],
    [ "Fossology\\UI\\Api\\Middlewares\\FossologyInitMiddleware", "dc/def/classFossology_1_1UI_1_1Api_1_1Middlewares_1_1FossologyInitMiddleware.html", null ],
    [ "FossologyUnicodeClean", "da/dd7/classFossologyUnicodeClean.html", null ],
    [ "fossologyUnitTestCase", null, [
      [ "TestFreshmeatRdfs", "d6/d07/classTestFreshmeatRdfs.html", null ],
      [ "TestReadinFile", "d1/d9b/classTestReadinFile.html", null ]
    ] ],
    [ "FreshmeatRdfs", "df/d99/classFreshmeatRdfs.html", null ],
    [ "GetFreshMeatRdf", "d0/d44/classGetFreshMeatRdf.html", null ],
    [ "globals", "d8/d11/structglobals.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Group", "d3/d1f/classFossology_1_1UI_1_1Api_1_1Models_1_1Group.html", null ],
    [ "group_manage", "d1/d76/classgroup__manage.html", null ],
    [ "Fossology\\UI\\Api\\Models\\GroupPermission", "d4/dfc/classFossology_1_1UI_1_1Api_1_1Models_1_1GroupPermission.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Hash", "d3/d97/classFossology_1_1UI_1_1Api_1_1Models_1_1Hash.html", null ],
    [ "Fossology\\Lib\\Data\\Highlight", "db/d39/classFossology_1_1Lib_1_1Data_1_1Highlight.html", null ],
    [ "Fossology\\Lib\\Dao\\HighlightDao", "d8/d27/classFossology_1_1Lib_1_1Dao_1_1HighlightDao.html", null ],
    [ "Fossology\\Lib\\View\\HighlightProcessor", "dd/de1/classFossology_1_1Lib_1_1View_1_1HighlightProcessor.html", null ],
    [ "Fossology\\Lib\\View\\HighlightRenderer", "d1/d94/classFossology_1_1Lib_1_1View_1_1HighlightRenderer.html", null ],
    [ "Fossology\\Lib\\View\\HighlightState", "d4/dc5/classFossology_1_1Lib_1_1View_1_1HighlightState.html", null ],
    [ "host_t", "d5/dcf/structhost__t.html", null ],
    [ "Fossology\\Lib\\Html\\HtmlElement", "d2/d0f/interfaceFossology_1_1Lib_1_1Html_1_1HtmlElement.html", [
      [ "Fossology\\Lib\\Html\\SimpleHtmlElement", "d0/d3a/classFossology_1_1Lib_1_1Html_1_1SimpleHtmlElement.html", [
        [ "Fossology\\Lib\\Html\\LinkElement", "d5/de2/classFossology_1_1Lib_1_1Html_1_1LinkElement.html", null ]
      ] ]
    ] ],
    [ "Fossology\\Lib\\Util\\HttpUtils", "de/db3/classFossology_1_1Lib_1_1Util_1_1HttpUtils.html", null ],
    [ "Fossology\\ReportImport\\ImportSource", "d9/d37/interfaceFossology_1_1ReportImport_1_1ImportSource.html", [
      [ "Fossology\\ReportImport\\SpdxThreeImportSource", "da/d69/classFossology_1_1ReportImport_1_1SpdxThreeImportSource.html", null ],
      [ "Fossology\\ReportImport\\SpdxTwoImportSource", "d6/de0/classFossology_1_1ReportImport_1_1SpdxTwoImportSource.html", null ],
      [ "Fossology\\ReportImport\\XmlImportSource", "d2/da2/classFossology_1_1ReportImport_1_1XmlImportSource.html", null ]
    ] ],
    [ "Fossology\\UI\\Api\\Models\\Info", "d2/d4d/classFossology_1_1UI_1_1Api_1_1Models_1_1Info.html", null ],
    [ "Fossology\\UI\\Api\\Models\\InfoType", "d6/dc1/classFossology_1_1UI_1_1Api_1_1Models_1_1InfoType.html", null ],
    [ "interface_connection", "d5/d1f/structinterface__connection.html", null ],
    [ "Fossology\\Lib\\Data\\Tree\\Item", "d1/d4d/classFossology_1_1Lib_1_1Data_1_1Tree_1_1Item.html", null ],
    [ "Fossology\\Lib\\Data\\Tree\\ItemTreeBounds", "d9/dc7/classFossology_1_1Lib_1_1Data_1_1Tree_1_1ItemTreeBounds.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Job", "dd/d7b/classFossology_1_1UI_1_1Api_1_1Models_1_1Job.html", null ],
    [ "job_t", "d2/d68/structjob__t.html", null ],
    [ "Fossology\\Lib\\Dao\\JobDao", "d4/d43/classFossology_1_1Lib_1_1Dao_1_1JobDao.html", null ],
    [ "Fossology\\UI\\Api\\Models\\JobQueue", "d1/d1c/classFossology_1_1UI_1_1Api_1_1Models_1_1JobQueue.html", null ],
    [ "LicenceAndMatchPositions", "dd/daf/structLicenceAndMatchPositions.html", null ],
    [ "Fossology\\UI\\Api\\Models\\License", "db/d34/classFossology_1_1UI_1_1Api_1_1Models_1_1License.html", [
      [ "Fossology\\UI\\Api\\Models\\LicenseDecision", "d0/d1a/classFossology_1_1UI_1_1Api_1_1Models_1_1LicenseDecision.html", null ]
    ] ],
    [ "license", "df/d72/structlicense.html", null ],
    [ "License", "d6/d58/structLicense.html", null ],
    [ "Fossology\\Lib\\Dao\\LicenseAcknowledgementDao", "de/d69/classFossology_1_1Lib_1_1Dao_1_1LicenseAcknowledgementDao.html", null ],
    [ "Fossology\\UI\\Api\\Models\\LicenseCandidate", "d6/d94/classFossology_1_1UI_1_1Api_1_1Models_1_1LicenseCandidate.html", null ],
    [ "Fossology\\Lib\\Data\\Clearing\\LicenseClearing", "d0/d7c/interfaceFossology_1_1Lib_1_1Data_1_1Clearing_1_1LicenseClearing.html", [
      [ "Fossology\\Lib\\Data\\Clearing\\AgentClearingEvent", "d5/da2/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1AgentClearingEvent.html", null ],
      [ "Fossology\\Lib\\Data\\Clearing\\ClearingEvent", "d5/d08/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingEvent.html", null ],
      [ "Fossology\\Lib\\Data\\Clearing\\ClearingResult", "d7/de2/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingResult.html", null ]
    ] ],
    [ "Fossology\\Lib\\Application\\LicenseCompatibilityRulesYamlExport", "d0/db8/classFossology_1_1Lib_1_1Application_1_1LicenseCompatibilityRulesYamlExport.html", null ],
    [ "Fossology\\Lib\\Application\\LicenseCompatibilityRulesYamlImport", "d5/d2b/classFossology_1_1Lib_1_1Application_1_1LicenseCompatibilityRulesYamlImport.html", null ],
    [ "Fossology\\Lib\\Application\\LicenseCsvExport", "d3/d54/classFossology_1_1Lib_1_1Application_1_1LicenseCsvExport.html", null ],
    [ "Fossology\\Lib\\Application\\LicenseCsvImport", "db/d40/classFossology_1_1Lib_1_1Application_1_1LicenseCsvImport.html", null ],
    [ "Fossology\\Lib\\Dao\\LicenseDao", "d2/d10/classFossology_1_1Lib_1_1Dao_1_1LicenseDao.html", null ],
    [ "osadl_convertor.LicenseHandler", "da/dbc/classosadl__convertor_1_1LicenseHandler.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\LicenseMap", "d5/ddf/classFossology_1_1Lib_1_1BusinessRules_1_1LicenseMap.html", null ],
    [ "Fossology\\Lib\\Data\\LicenseMatch", "d8/d1b/classFossology_1_1Lib_1_1Data_1_1LicenseMatch.html", null ],
    [ "LicenseMatch", "d8/db8/classLicenseMatch.html", null ],
    [ "Fossology\\Lib\\Data\\LicenseRef", "d6/d82/classFossology_1_1Lib_1_1Data_1_1LicenseRef.html", [
      [ "Fossology\\Lib\\Data\\License", "d7/db3/classFossology_1_1Lib_1_1Data_1_1License.html", null ]
    ] ],
    [ "Licenses", "d7/da8/structLicenses.html", null ],
    [ "licenseSpec", "db/dab/structlicenseSpec.html", null ],
    [ "Fossology\\UI\\Api\\Models\\LicenseStandardComment", "db/d47/classFossology_1_1UI_1_1Api_1_1Models_1_1LicenseStandardComment.html", null ],
    [ "Fossology\\Lib\\Dao\\LicenseStdCommentDao", "d2/d49/classFossology_1_1Lib_1_1Dao_1_1LicenseStdCommentDao.html", null ],
    [ "licensetext", "d5/d1a/structlicensetext.html", null ],
    [ "list", "d8/d10/structlist.html", null ],
    [ "listitem", "d9/df5/structlistitem.html", null ],
    [ "log_event_args", "db/dfc/structlog__event__args.html", null ],
    [ "log_t", "d2/ddc/structlog__t.html", null ],
    [ "match", "de/d90/structmatch.html", null ],
    [ "Match", "d2/db6/structMatch.html", null ],
    [ "MatchCallbacks", "dc/df3/structMatchCallbacks.html", null ],
    [ "MatchPositionAndType", "d2/d3c/structMatchPositionAndType.html", null ],
    [ "osadl_convertor.MatrixItem", "d4/d90/classosadl__convertor_1_1MatrixItem.html", null ],
    [ "Fossology\\Lib\\UI\\Component\\Menu", "d7/db3/classFossology_1_1Lib_1_1UI_1_1Component_1_1Menu.html", null ],
    [ "menu", "d7/d3d/classmenu.html", null ],
    [ "Fossology\\Lib\\UI\\MenuHook", "d9/d18/classFossology_1_1Lib_1_1UI_1_1MenuHook.html", null ],
    [ "Fossology\\Lib\\UI\\MenuRenderer", "de/d88/classFossology_1_1Lib_1_1UI_1_1MenuRenderer.html", null ],
    [ "meta_agent_t", "de/d5d/structmeta__agent__t.html", null ],
    [ "Fossology\\Lib\\UI\\Component\\MicroMenu", "d1/dfa/classFossology_1_1Lib_1_1UI_1_1Component_1_1MicroMenu.html", null ],
    [ "mm_cache", "d3/dfe/structmm__cache.html", null ],
    [ "MonkState", "df/de7/structMonkState.html", null ],
    [ "ScanDeps.Parsers.NPMParser", "db/de7/classScanDeps_1_1Parsers_1_1NPMParser.html", null ],
    [ "object", null, [
      [ "FoScanner.CliOptions.CliOptions", "dc/d5e/classFoScanner_1_1CliOptions_1_1CliOptions.html", null ],
      [ "FoScanner.Packages.Packages", "d2/df1/classFoScanner_1_1Packages_1_1Packages.html", null ]
    ] ],
    [ "Fossology\\UI\\Api\\Models\\Obligation", "d0/dba/classFossology_1_1UI_1_1Api_1_1Models_1_1Obligation.html", null ],
    [ "Fossology\\Lib\\Application\\ObligationCsvExport", "d1/d70/classFossology_1_1Lib_1_1Application_1_1ObligationCsvExport.html", null ],
    [ "Fossology\\Lib\\Application\\ObligationCsvImport", "df/dad/classFossology_1_1Lib_1_1Application_1_1ObligationCsvImport.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\ObligationMap", "db/d30/classFossology_1_1Lib_1_1BusinessRules_1_1ObligationMap.html", null ],
    [ "Fossology\\Lib\\Report\\ObligationsGetter", "d6/d08/classFossology_1_1Lib_1_1Report_1_1ObligationsGetter.html", null ],
    [ "ObligationsToLicenses", "d6/d36/classObligationsToLicenses.html", null ],
    [ "OjoAgent", "df/da5/classOjoAgent.html", null ],
    [ "OjoCliOptions", "dd/d23/classOjoCliOptions.html", null ],
    [ "OjoDatabaseEntry", "d8/d65/structOjoDatabaseEntry.html", null ],
    [ "ojomatch", "db/d12/structojomatch.html", null ],
    [ "OjoState", "d0/d48/classOjoState.html", null ],
    [ "Fossology\\UI\\Api\\Models\\OneShot", "df/da0/classFossology_1_1UI_1_1Api_1_1Models_1_1OneShot.html", null ],
    [ "Fossology\\Lib\\Util\\OsselotLookupHelper", "de/d5d/classFossology_1_1Lib_1_1Util_1_1OsselotLookupHelper.html", null ],
    [ "Fossology\\Lib\\Report\\OtherGetter", "d0/df4/classFossology_1_1Lib_1_1Report_1_1OtherGetter.html", null ],
    [ "overlappingMatch", "d2/d16/classoverlappingMatch.html", null ],
    [ "Fossology\\Lib\\Data\\Package\\Package", "d1/da3/classFossology_1_1Lib_1_1Data_1_1Package_1_1Package.html", null ],
    [ "package_struct", "da/d25/structpackage__struct.html", null ],
    [ "Fossology\\Lib\\Dao\\PackageDao", "d9/d45/classFossology_1_1Lib_1_1Dao_1_1PackageDao.html", null ],
    [ "Fossology\\Lib\\View\\PagedResult", "df/dfd/classFossology_1_1Lib_1_1View_1_1PagedResult.html", [
      [ "Fossology\\Lib\\View\\PagedHexResult", "d6/dab/classFossology_1_1Lib_1_1View_1_1PagedHexResult.html", null ],
      [ "Fossology\\Lib\\View\\PagedTextResult", "d2/da1/classFossology_1_1Lib_1_1View_1_1PagedTextResult.html", null ],
      [ "Fossology\\Lib\\View\\TestPagedResult", "d5/dce/classFossology_1_1Lib_1_1View_1_1TestPagedResult.html", null ]
    ] ],
    [ "PairPosOff", "d0/de9/structPairPosOff.html", null ],
    [ "param", "de/dd5/structparam.html", null ],
    [ "ParentInfo", "d3/dbf/structParentInfo.html", null ],
    [ "parseBrowseMenu", "d9/d35/classparseBrowseMenu.html", null ],
    [ "parseFolderPath", "d9/def/classparseFolderPath.html", null ],
    [ "parseLicenseGrpTbl", "dd/d8a/classparseLicenseGrpTbl.html", null ],
    [ "parseLicenseTbl", "d4/de7/classparseLicenseTbl.html", null ],
    [ "parseLicenseTblDirs", "d1/d9e/classparseLicenseTblDirs.html", null ],
    [ "parseMiniMenu", "db/d26/classparseMiniMenu.html", null ],
    [ "parsePgLinks", "d6/d79/classparsePgLinks.html", null ],
    [ "ScanDeps.Parsers.Parser", "d2/dcb/classScanDeps_1_1Parsers_1_1Parser.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Permissions", "db/d0d/classFossology_1_1UI_1_1Api_1_1Models_1_1Permissions.html", null ],
    [ "permlist", "d3/d9a/structpermlist.html", null ],
    [ "Fossology\\Lib\\Dao\\PfileDao", "d6/df2/classFossology_1_1Lib_1_1Dao_1_1PfileDao.html", null ],
    [ "fo::PGresultDeleter", "dc/d37/classfo_1_1PGresultDeleter.html", null ],
    [ "Fossology\\Lib\\Plugin\\Plugin", "d8/d3d/interfaceFossology_1_1Lib_1_1Plugin_1_1Plugin.html", [
      [ "FO_Plugin", "d7/d54/classFO__Plugin.html", [
        [ "AjaxClearingView", "db/d93/classAjaxClearingView.html", null ],
        [ "AjaxNoticeFiles", "df/da2/classAjaxNoticeFiles.html", null ],
        [ "ClearingView", "dd/d85/classClearingView.html", null ],
        [ "CopyrightHistogramProcessPost", "d7/ddc/classCopyrightHistogramProcessPost.html", null ],
        [ "FossdashConfig", "d9/df8/classFossdashConfig.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxShowJobs", "dc/db1/classFossology_1_1UI_1_1Ajax_1_1AjaxShowJobs.html", null ],
        [ "HistogramBase", "dd/d3e/classHistogramBase.html", [
          [ "CopyrightHistogram", "d2/d9e/classCopyrightHistogram.html", null ],
          [ "EccHistogram", "d0/d27/classEccHistogram.html", null ],
          [ "EmailHistogram", "df/dc3/classEmailHistogram.html", null ],
          [ "IpraHistogram", "d7/da3/classIpraHistogram.html", null ],
          [ "KeywordHistogram", "de/da6/classKeywordHistogram.html", null ]
        ] ],
        [ "LicenseListFiles", "db/db8/classLicenseListFiles.html", null ],
        [ "PopupLicense", "d6/d22/classPopupLicense.html", null ],
        [ "SpashtCopyrightHistogramProcessPost", "d6/d24/classSpashtCopyrightHistogramProcessPost.html", null ],
        [ "UIExportList", "dc/d0e/classUIExportList.html", null ],
        [ "acme_review", "d5/ded/classacme__review.html", null ],
        [ "acme_review", "d5/ded/classacme__review.html", null ],
        [ "admin_bucket_pool", "d4/d07/classadmin__bucket__pool.html", null ],
        [ "admin_folder_delete", "da/da2/classadmin__folder__delete.html", null ],
        [ "admin_license_file", "d4/d2a/classadmin__license__file.html", null ],
        [ "admin_obligation_file", "d9/ddd/classadmin__obligation__file.html", null ],
        [ "admin_scheduler", "d0/dcd/classadmin__scheduler.html", null ],
        [ "admin_tag", "df/da9/classadmin__tag.html", null ],
        [ "admin_tag_manage", "df/d64/classadmin__tag__manage.html", null ],
        [ "agent_copyright_once", "d9/d74/classagent__copyright__once.html", null ],
        [ "agent_demomod", "da/d85/classagent__demomod.html", null ],
        [ "agent_nomos_once", "dd/d56/classagent__nomos__once.html", null ],
        [ "agent_wget_agent", "da/dd1/classagent__wget__agent.html", null ],
        [ "ajax_filebucket", "d8/d14/classajax__filebucket.html", null ],
        [ "ajax_filelic", "d2/d31/classajax__filelic.html", null ],
        [ "ajax_schedule_agent", "da/d4a/classajax__schedule__agent.html", null ],
        [ "ajax_tags", "dd/d6e/classajax__tags.html", null ],
        [ "changeLicenseProcessPost", "de/d0c/classchangeLicenseProcessPost.html", null ],
        [ "copyright_list", "d3/dc2/classcopyright__list.html", null ],
        [ "core_auth", "d9/db1/classcore__auth.html", null ],
        [ "core_debug", "df/dba/classcore__debug.html", null ],
        [ "core_debug_fileloc", "d1/dde/classcore__debug__fileloc.html", null ],
        [ "core_debug_menus", "d1/d2e/classcore__debug__menus.html", null ],
        [ "core_init", "de/d44/classcore__init.html", null ],
        [ "core_smauth", "d0/da0/classcore__smauth.html", null ],
        [ "core_uploads", "d4/d81/classcore__uploads.html", null ],
        [ "dashboard", "d7/d6d/classdashboard.html", null ],
        [ "dashboardReporting", "d6/dee/classdashboardReporting.html", null ],
        [ "debug_flush_cache", "de/d1c/classdebug__flush__cache.html", null ],
        [ "debug_user", "d9/db6/classdebug__user.html", null ],
        [ "foconfig", "d3/d19/classfoconfig.html", null ],
        [ "folder_create", "df/dd4/classfolder__create.html", null ],
        [ "folder_properties", "dc/d9f/classfolder__properties.html", null ],
        [ "group_add", "db/d99/classgroup__add.html", null ],
        [ "list_bucket_files", "d7/d29/classlist__bucket__files.html", null ],
        [ "maintagent", "d7/d9e/classmaintagent.html", null ],
        [ "search", "d3/d31/classsearch.html", null ],
        [ "showjobs", "d4/d76/classshowjobs.html", null ],
        [ "size_dashboard", "db/d3a/classsize__dashboard.html", null ],
        [ "ui_browse", "db/d34/classui__browse.html", null ],
        [ "ui_buckets", "da/d1c/classui__buckets.html", null ],
        [ "ui_demomod", "d3/d7e/classui__demomod.html", null ],
        [ "ui_diff_buckets", "d8/d23/classui__diff__buckets.html", null ],
        [ "ui_download", "da/d73/classui__download.html", null ],
        [ "ui_nomos_diff", "d6/dc1/classui__nomos__diff.html", null ],
        [ "ui_picker", "d6/da7/classui__picker.html", null ],
        [ "ui_refresh", "da/d41/classui__refresh.html", null ],
        [ "ui_report_conf", "d5/d1a/classui__report__conf.html", null ],
        [ "ui_reunpack", "da/d3c/classui__reunpack.html", null ],
        [ "ui_spasht", "d6/d03/classui__spasht.html", null ],
        [ "ui_tag", "d8/d4b/classui__tag.html", null ],
        [ "ui_topnav", "d1/dbc/classui__topnav.html", null ],
        [ "ui_treenav", "de/d07/classui__treenav.html", null ],
        [ "ui_view", "d3/d90/classui__view.html", null ],
        [ "ui_view_info", "d5/dd2/classui__view__info.html", null ],
        [ "upload_properties", "dc/d1c/classupload__properties.html", null ],
        [ "upload_tagging", "d5/d85/classupload__tagging.html", null ],
        [ "user_del", "de/dad/classuser__del.html", null ]
      ] ],
      [ "Fossology\\Lib\\Plugin\\AgentPlugin", "de/d33/classFossology_1_1Lib_1_1Plugin_1_1AgentPlugin.html", [
        [ "Adj2nestAgentPlugin", "d9/dd0/classAdj2nestAgentPlugin.html", null ],
        [ "BucketAgentPlugin", "d1/df3/classBucketAgentPlugin.html", null ],
        [ "CopyrightAgentPlugin", "d3/ddc/classCopyrightAgentPlugin.html", null ],
        [ "DeciderAgentPlugin", "d9/d26/classDeciderAgentPlugin.html", null ],
        [ "EccAgentPlugin", "d1/dda/classEccAgentPlugin.html", null ],
        [ "Fossology\\CliXml\\UI\\CliXmlAgentPlugin", "d3/de2/classFossology_1_1CliXml_1_1UI_1_1CliXmlAgentPlugin.html", null ],
        [ "Fossology\\Compatibility\\Ui\\CompatibilityAgentPlugin", "d3/d3b/classFossology_1_1Compatibility_1_1Ui_1_1CompatibilityAgentPlugin.html", null ],
        [ "Fossology\\CycloneDX\\UI\\CycloneDXAgentPlugin", "d9/dc8/classFossology_1_1CycloneDX_1_1UI_1_1CycloneDXAgentPlugin.html", null ],
        [ "Fossology\\DeciderJob\\UI\\DeciderJobAgentPlugin", "d1/d09/classFossology_1_1DeciderJob_1_1UI_1_1DeciderJobAgentPlugin.html", null ],
        [ "Fossology\\DecisionExporter\\UI\\DecisionExporterAgentPlugin", "d3/d21/classFossology_1_1DecisionExporter_1_1UI_1_1DecisionExporterAgentPlugin.html", null ],
        [ "Fossology\\DecisionImporter\\UI\\FoDecisionImporter", "df/da9/classFossology_1_1DecisionImporter_1_1UI_1_1FoDecisionImporter.html", null ],
        [ "Fossology\\Ninka\\Ui\\NinkaAgentPlugin", "db/d93/classFossology_1_1Ninka_1_1Ui_1_1NinkaAgentPlugin.html", null ],
        [ "Fossology\\Ojo\\Ui\\OjosAgentPlugin", "d1/d1a/classFossology_1_1Ojo_1_1Ui_1_1OjosAgentPlugin.html", null ],
        [ "Fossology\\ReadmeOSS\\UI\\ReadMeOssAgentPlugin", "d3/ddc/classFossology_1_1ReadmeOSS_1_1UI_1_1ReadMeOssAgentPlugin.html", null ],
        [ "Fossology\\Reuser\\ReuserAgentPlugin", "dc/d80/classFossology_1_1Reuser_1_1ReuserAgentPlugin.html", null ],
        [ "Fossology\\Scancode\\Ui\\ScancodesAgentPlugin", "d1/d6e/classFossology_1_1Scancode_1_1Ui_1_1ScancodesAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\DepFiveAgentPlugin", "d8/dac/classFossology_1_1Spdx_1_1UI_1_1DepFiveAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxThreeJsonAgentPlugin", "db/d40/classFossology_1_1Spdx_1_1UI_1_1SpdxThreeJsonAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxThreeJsonldAgentPlugin", "da/d27/classFossology_1_1Spdx_1_1UI_1_1SpdxThreeJsonldAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxThreeRDFAgentPlugin", "d3/d9a/classFossology_1_1Spdx_1_1UI_1_1SpdxThreeRDFAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxThreeTagValueAgentPlugin", "de/df9/classFossology_1_1Spdx_1_1UI_1_1SpdxThreeTagValueAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxTwoAgentPlugin", "d6/d2f/classFossology_1_1Spdx_1_1UI_1_1SpdxTwoAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxTwoCommaSeparatedValuesAgentPlugin", "d7/d69/classFossology_1_1Spdx_1_1UI_1_1SpdxTwoCommaSeparatedValuesAgentPlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxTwoTagValueAgentPlugin", "d2/dfe/classFossology_1_1Spdx_1_1UI_1_1SpdxTwoTagValueAgentPlugin.html", null ],
        [ "Fossology\\UnifiedReport\\UI\\UnifiedReportAgentPlugin", "d1/d0c/classFossology_1_1UnifiedReport_1_1UI_1_1UnifiedReportAgentPlugin.html", null ],
        [ "IpraAgentPlugin", "d6/d16/classIpraAgentPlugin.html", null ],
        [ "KeywordAgentPlugin", "d8/daa/classKeywordAgentPlugin.html", null ],
        [ "MimetypeAgentPlugin", "df/d4c/classMimetypeAgentPlugin.html", null ],
        [ "MonkAgentPlugin", "d6/dfb/classMonkAgentPlugin.html", null ],
        [ "MonkBulkAgentPlugin", "d5/d12/classMonkBulkAgentPlugin.html", null ],
        [ "NomosAgentPlugin", "da/d3e/classNomosAgentPlugin.html", null ],
        [ "PkgAgentPlugin", "d9/d5e/classPkgAgentPlugin.html", null ],
        [ "ReportImportAgentPlugin", "d6/dee/classReportImportAgentPlugin.html", null ],
        [ "ResoAgentPlugin", "d4/df8/classResoAgentPlugin.html", null ],
        [ "ScanossAgentPlugin", "de/d12/classScanossAgentPlugin.html", null ],
        [ "SpashtAgentPlugin", "d2/d4e/classSpashtAgentPlugin.html", null ],
        [ "UnpackAgentPlugin", "d0/dc0/classUnpackAgentPlugin.html", null ],
        [ "softwareHeritageAgentPlugin", "d0/d04/classsoftwareHeritageAgentPlugin.html", null ]
      ] ],
      [ "Fossology\\Lib\\Plugin\\DefaultPlugin", "d4/d53/classFossology_1_1Lib_1_1Plugin_1_1DefaultPlugin.html", [
        [ "AdminContentDelete", "d9/ddd/classAdminContentDelete.html", null ],
        [ "AdminContentMove", "de/dad/classAdminContentMove.html", null ],
        [ "AgentAdder", "db/d5e/classAgentAdder.html", null ],
        [ "AjaxSHDetailsBrowser", "d2/da7/classAjaxSHDetailsBrowser.html", null ],
        [ "AjaxUploadAgents", "d6/db7/classAjaxUploadAgents.html", null ],
        [ "ChangeLicenseBulk", "dc/dce/classChangeLicenseBulk.html", null ],
        [ "Fossology\\Agent\\Copyright\\UI\\Xpview", "d4/dfa/classFossology_1_1Agent_1_1Copyright_1_1UI_1_1Xpview.html", [
          [ "Fossology\\Agent\\Copyright\\UI\\CopyrightView", "d6/d83/classFossology_1_1Agent_1_1Copyright_1_1UI_1_1CopyrightView.html", null ],
          [ "Fossology\\Agent\\Copyright\\UI\\EccView", "d6/d2a/classFossology_1_1Agent_1_1Copyright_1_1UI_1_1EccView.html", null ],
          [ "Fossology\\Agent\\Copyright\\UI\\IpraView", "dc/d6c/classFossology_1_1Agent_1_1Copyright_1_1UI_1_1IpraView.html", null ],
          [ "Fossology\\Agent\\Copyright\\UI\\KeywordView", "d4/df3/classFossology_1_1Agent_1_1Copyright_1_1UI_1_1KeywordView.html", null ]
        ] ],
        [ "Fossology\\CliXml\\UI\\CliXmlGeneratorUi", "d8/d6a/classFossology_1_1CliXml_1_1UI_1_1CliXmlGeneratorUi.html", null ],
        [ "Fossology\\CycloneDX\\UI\\CycloneDXGeneratorUi", "d6/d9c/classFossology_1_1CycloneDX_1_1UI_1_1CycloneDXGeneratorUi.html", null ],
        [ "Fossology\\DecisionExporter\\UI\\FoDecisionExporter", "da/d68/classFossology_1_1DecisionExporter_1_1UI_1_1FoDecisionExporter.html", null ],
        [ "Fossology\\DecisionImporter\\UI\\AgentDecisionImporterPlugin", "d2/d25/classFossology_1_1DecisionImporter_1_1UI_1_1AgentDecisionImporterPlugin.html", null ],
        [ "Fossology\\DelAgent\\UI\\Page\\AdminUploadDelete", "d1/d97/classFossology_1_1DelAgent_1_1UI_1_1Page_1_1AdminUploadDelete.html", null ],
        [ "Fossology\\DelAgent\\UI\\Page\\BrowseUploadDelete", "dd/dd3/classFossology_1_1DelAgent_1_1UI_1_1Page_1_1BrowseUploadDelete.html", null ],
        [ "Fossology\\DemoHello\\DemoHello", "d0/d0a/classFossology_1_1DemoHello_1_1DemoHello.html", null ],
        [ "Fossology\\Lib\\Plugin\\TestPlugin", "da/dab/classFossology_1_1Lib_1_1Plugin_1_1TestPlugin.html", null ],
        [ "Fossology\\Monk\\AdminMonkRevision", "df/d7e/classFossology_1_1Monk_1_1AdminMonkRevision.html", null ],
        [ "Fossology\\Monk\\UI\\OneShot", "da/d38/classFossology_1_1Monk_1_1UI_1_1OneShot.html", null ],
        [ "Fossology\\ReadmeOSS\\UI\\ReadMeOssPlugin", "db/d48/classFossology_1_1ReadmeOSS_1_1UI_1_1ReadMeOssPlugin.html", null ],
        [ "Fossology\\Reuser\\ReuserPlugin", "d2/dad/classFossology_1_1Reuser_1_1ReuserPlugin.html", null ],
        [ "Fossology\\SoftwareHeritage\\UI\\softwareHeritagePlugin", "d6/dbe/classFossology_1_1SoftwareHeritage_1_1UI_1_1softwareHeritagePlugin.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxThreeGeneratorUi", "d9/d47/classFossology_1_1Spdx_1_1UI_1_1SpdxThreeGeneratorUi.html", null ],
        [ "Fossology\\Spdx\\UI\\SpdxTwoGeneratorUi", "d7/db3/classFossology_1_1Spdx_1_1UI_1_1SpdxTwoGeneratorUi.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxAdminScheduler", "d7/d26/classFossology_1_1UI_1_1Ajax_1_1AjaxAdminScheduler.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxAllJobStatus", "d1/d8c/classFossology_1_1UI_1_1Ajax_1_1AjaxAllJobStatus.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxBrowse", "df/d1c/classFossology_1_1UI_1_1Ajax_1_1AjaxBrowse.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxBulkHistory", "db/da4/classFossology_1_1UI_1_1Ajax_1_1AjaxBulkHistory.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxExplorer", "db/def/classFossology_1_1UI_1_1Ajax_1_1AjaxExplorer.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxFileBrowser", "d7/db9/classFossology_1_1UI_1_1Ajax_1_1AjaxFileBrowser.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxFolderContents", "d8/dd5/classFossology_1_1UI_1_1Ajax_1_1AjaxFolderContents.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxJobInfo", "df/d09/classFossology_1_1UI_1_1Ajax_1_1AjaxJobInfo.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxJobStatus", "d4/df4/classFossology_1_1UI_1_1Ajax_1_1AjaxJobStatus.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxLicenseStdAcknowledgements", "d8/df7/classFossology_1_1UI_1_1Ajax_1_1AjaxLicenseStdAcknowledgements.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxLicenseStdComments", "d1/d16/classFossology_1_1UI_1_1Ajax_1_1AjaxLicenseStdComments.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxManageToken", "dc/de8/classFossology_1_1UI_1_1Ajax_1_1AjaxManageToken.html", null ],
        [ "Fossology\\UI\\Ajax\\AjaxReuseReport", "d5/d98/classFossology_1_1UI_1_1Ajax_1_1AjaxReuseReport.html", null ],
        [ "Fossology\\UI\\Ajax\\ScheduleAgent", "d9/d69/classFossology_1_1UI_1_1Ajax_1_1ScheduleAgent.html", null ],
        [ "Fossology\\UI\\Page\\AboutPage", "db/dd3/classFossology_1_1UI_1_1Page_1_1AboutPage.html", null ],
        [ "Fossology\\UI\\Page\\AdminAllLicenseToCSV", "d8/df3/classFossology_1_1UI_1_1Page_1_1AdminAllLicenseToCSV.html", null ],
        [ "Fossology\\UI\\Page\\AdminAllLicenseToJSON", "d8/d23/classFossology_1_1UI_1_1Page_1_1AdminAllLicenseToJSON.html", null ],
        [ "Fossology\\UI\\Page\\AdminGroupDelete", "d0/d2f/classFossology_1_1UI_1_1Page_1_1AdminGroupDelete.html", null ],
        [ "Fossology\\UI\\Page\\AdminGroupEdit", "dd/df1/classFossology_1_1UI_1_1Page_1_1AdminGroupEdit.html", null ],
        [ "Fossology\\UI\\Page\\AdminGroupUsers", "d5/d6a/classFossology_1_1UI_1_1Page_1_1AdminGroupUsers.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseAcknowledgements", "d2/da6/classFossology_1_1UI_1_1Page_1_1AdminLicenseAcknowledgements.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseCandidate", "d9/dc4/classFossology_1_1UI_1_1Page_1_1AdminLicenseCandidate.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseCompatibilityRules", "d5/d06/classFossology_1_1UI_1_1Page_1_1AdminLicenseCompatibilityRules.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseFromCSV", "dc/dc8/classFossology_1_1UI_1_1Page_1_1AdminLicenseFromCSV.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseFromYAML", "d4/d29/classFossology_1_1UI_1_1Page_1_1AdminLicenseFromYAML.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseStdComments", "db/d3e/classFossology_1_1UI_1_1Page_1_1AdminLicenseStdComments.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseToCSV", "db/dd6/classFossology_1_1UI_1_1Page_1_1AdminLicenseToCSV.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseToJSON", "da/dbc/classFossology_1_1UI_1_1Page_1_1AdminLicenseToJSON.html", null ],
        [ "Fossology\\UI\\Page\\AdminLicenseToYAML", "d3/d63/classFossology_1_1UI_1_1Page_1_1AdminLicenseToYAML.html", null ],
        [ "Fossology\\UI\\Page\\AdminObligationFromCSV", "d2/da3/classFossology_1_1UI_1_1Page_1_1AdminObligationFromCSV.html", null ],
        [ "Fossology\\UI\\Page\\AdminObligationToCSV", "d4/d3f/classFossology_1_1UI_1_1Page_1_1AdminObligationToCSV.html", null ],
        [ "Fossology\\UI\\Page\\AdminObligationToJSON", "dd/d7b/classFossology_1_1UI_1_1Page_1_1AdminObligationToJSON.html", null ],
        [ "Fossology\\UI\\Page\\AdviceLicense", "d2/da2/classFossology_1_1UI_1_1Page_1_1AdviceLicense.html", null ],
        [ "Fossology\\UI\\Page\\AllJobStatus", "dc/d88/classFossology_1_1UI_1_1Page_1_1AllJobStatus.html", null ],
        [ "Fossology\\UI\\Page\\BrowseLicense", "d2/de4/classFossology_1_1UI_1_1Page_1_1BrowseLicense.html", null ],
        [ "Fossology\\UI\\Page\\GettingStartedPage", "d0/d34/classFossology_1_1UI_1_1Page_1_1GettingStartedPage.html", null ],
        [ "Fossology\\UI\\Page\\HomePage", "d8/d12/classFossology_1_1UI_1_1Page_1_1HomePage.html", null ],
        [ "Fossology\\UI\\Page\\ThirdPartyLicensesPage", "d6/d60/classFossology_1_1UI_1_1Page_1_1ThirdPartyLicensesPage.html", null ],
        [ "Fossology\\UI\\Page\\UploadPageBase", "d1/d96/classFossology_1_1UI_1_1Page_1_1UploadPageBase.html", [
          [ "Fossology\\UI\\Page\\UploadFilePage", "d3/dc4/classFossology_1_1UI_1_1Page_1_1UploadFilePage.html", [
            [ "Fossology\\UI\\Api\\Helper\\UploadHelper\\HelperToUploadFilePage", "db/dd9/classFossology_1_1UI_1_1Api_1_1Helper_1_1UploadHelper_1_1HelperToUploadFilePage.html", null ]
          ] ],
          [ "Fossology\\UI\\Page\\UploadSrvPage", "d6/d54/classFossology_1_1UI_1_1Page_1_1UploadSrvPage.html", [
            [ "Fossology\\UI\\Api\\Helper\\UploadHelper\\HelperToUploadSrvPage", "d4/d1d/classFossology_1_1UI_1_1Api_1_1Helper_1_1UploadHelper_1_1HelperToUploadSrvPage.html", null ]
          ] ],
          [ "Fossology\\UI\\Page\\UploadUrlPage", "d1/db1/classFossology_1_1UI_1_1Page_1_1UploadUrlPage.html", [
            [ "Fossology\\UI\\Api\\Helper\\UploadHelper\\HelperToUploadUrlPage", "d8/db0/classFossology_1_1UI_1_1Api_1_1Helper_1_1UploadHelper_1_1HelperToUploadUrlPage.html", null ]
          ] ],
          [ "Fossology\\UI\\Page\\UploadVcsPage", "da/d7c/classFossology_1_1UI_1_1Page_1_1UploadVcsPage.html", [
            [ "Fossology\\UI\\Api\\Helper\\UploadHelper\\HelperToUploadVcsPage", "d6/dc7/classFossology_1_1UI_1_1Api_1_1Helper_1_1UploadHelper_1_1HelperToUploadVcsPage.html", null ]
          ] ]
        ] ],
        [ "Fossology\\UnifiedReport\\UI\\FoUnifiedReportGenerator", "dd/dc6/classFossology_1_1UnifiedReport_1_1UI_1_1FoUnifiedReportGenerator.html", null ],
        [ "ReportImportPlugin", "dd/d23/classReportImportPlugin.html", null ],
        [ "UploadInstructions", "d5/d3c/classUploadInstructions.html", null ],
        [ "UploadPermissionPage", "db/d88/classUploadPermissionPage.html", null ],
        [ "UserEditPage", "d8/d92/classUserEditPage.html", null ],
        [ "ui_file_browse", "d1/d90/classui__file__browse.html", null ],
        [ "user_add", "d8/db9/classuser__add.html", null ]
      ] ]
    ] ],
    [ "point", "d8/dae/structpoint.html", null ],
    [ "Fossology\\Lib\\Util\\PurlOperations", "de/deb/classFossology_1_1Lib_1_1Util_1_1PurlOperations.html", null ],
    [ "ScanDeps.Parsers.PythonParser", "d9/d49/classScanDeps_1_1Parsers_1_1PythonParser.html", null ],
    [ "fo::QueryResult", "dc/d29/classfo_1_1QueryResult.html", null ],
    [ "ReadInputFile", "da/d89/classReadInputFile.html", null ],
    [ "Fossology\\Lib\\Test\\Reflectory", "d6/dc8/classFossology_1_1Lib_1_1Test_1_1Reflectory.html", null ],
    [ "regex_file_struct", "d0/dca/structregex__file__struct.html", null ],
    [ "RegexConfProvider", "d7/dcd/classRegexConfProvider.html", null ],
    [ "RepMmapStruct", "df/dab/structRepMmapStruct.html", null ],
    [ "Fossology\\ReportImport\\ReportImportConfiguration", "de/d5f/classFossology_1_1ReportImport_1_1ReportImportConfiguration.html", null ],
    [ "Fossology\\ReportImport\\ReportImportData", "d7/d11/classFossology_1_1ReportImport_1_1ReportImportData.html", null ],
    [ "Fossology\\ReportImport\\ReportImportDataItem", "d7/d94/classFossology_1_1ReportImport_1_1ReportImportDataItem.html", null ],
    [ "Fossology\\ReportImport\\ReportImportHelper", "db/dcb/classFossology_1_1ReportImport_1_1ReportImportHelper.html", null ],
    [ "Fossology\\ReportImport\\ReportImportSink", "d6/d83/classFossology_1_1ReportImport_1_1ReportImportSink.html", null ],
    [ "ReportStatic", "d0/da3/classReportStatic.html", null ],
    [ "ReportSummary", "d3/de4/classReportSummary.html", null ],
    [ "Fossology\\Lib\\Report\\ReportUtils", "d4/d3c/classFossology_1_1Lib_1_1Report_1_1ReportUtils.html", null ],
    [ "FoScanner.RepoSetup.RepoSetup", "d3/d73/classFoScanner_1_1RepoSetup_1_1RepoSetup.html", null ],
    [ "Fossology\\Lib\\Application\\RepositoryApi", "d2/d9c/classFossology_1_1Lib_1_1Application_1_1RepositoryApi.html", null ],
    [ "reqcols", "db/d03/structreqcols.html", null ],
    [ "Reso", "d0/de2/classReso.html", null ],
    [ "Fossology\\UI\\Api\\Middlewares\\RestAuthMiddleware", "d4/d1e/classFossology_1_1UI_1_1Api_1_1Middlewares_1_1RestAuthMiddleware.html", null ],
    [ "Fossology\\UI\\Api\\Controllers\\RestController", "db/d5a/classFossology_1_1UI_1_1Api_1_1Controllers_1_1RestController.html", [
      [ "Fossology\\UI\\Api\\Controllers\\AuthController", "d1/db1/classFossology_1_1UI_1_1Api_1_1Controllers_1_1AuthController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\BadRequestController", "d0/d1d/classFossology_1_1UI_1_1Api_1_1Controllers_1_1BadRequestController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\ConfController", "d5/d79/classFossology_1_1UI_1_1Api_1_1Controllers_1_1ConfController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\CopyrightController", "dc/de0/classFossology_1_1UI_1_1Api_1_1Controllers_1_1CopyrightController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\CustomiseController", "d4/df3/classFossology_1_1UI_1_1Api_1_1Controllers_1_1CustomiseController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\FileInfoController", "d7/d64/classFossology_1_1UI_1_1Api_1_1Controllers_1_1FileInfoController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\FileSearchController", "d2/d1b/classFossology_1_1UI_1_1Api_1_1Controllers_1_1FileSearchController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\FolderController", "d3/d80/classFossology_1_1UI_1_1Api_1_1Controllers_1_1FolderController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\GroupController", "d8/d53/classFossology_1_1UI_1_1Api_1_1Controllers_1_1GroupController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\InfoController", "de/d6d/classFossology_1_1UI_1_1Api_1_1Controllers_1_1InfoController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\JobController", "de/d20/classFossology_1_1UI_1_1Api_1_1Controllers_1_1JobController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\LicenseController", "d3/dee/classFossology_1_1UI_1_1Api_1_1Controllers_1_1LicenseController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\MaintenanceController", "da/d14/classFossology_1_1UI_1_1Api_1_1Controllers_1_1MaintenanceController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\ObligationController", "df/d3c/classFossology_1_1UI_1_1Api_1_1Controllers_1_1ObligationController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\OneShotController", "d0/df0/classFossology_1_1UI_1_1Api_1_1Controllers_1_1OneShotController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\OsselotController", "d0/daf/classFossology_1_1UI_1_1Api_1_1Controllers_1_1OsselotController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\OverviewController", "db/dcb/classFossology_1_1UI_1_1Api_1_1Controllers_1_1OverviewController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\ReportController", "d4/d1a/classFossology_1_1UI_1_1Api_1_1Controllers_1_1ReportController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\SearchController", "d6/d88/classFossology_1_1UI_1_1Api_1_1Controllers_1_1SearchController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\UploadController", "d0/d43/classFossology_1_1UI_1_1Api_1_1Controllers_1_1UploadController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\UploadTreeController", "d2/dce/classFossology_1_1UI_1_1Api_1_1Controllers_1_1UploadTreeController.html", null ],
      [ "Fossology\\UI\\Api\\Controllers\\UserController", "d0/d10/classFossology_1_1UI_1_1Api_1_1Controllers_1_1UserController.html", null ]
    ] ],
    [ "Fossology\\UI\\Api\\Helper\\RestHelper", "df/d33/classFossology_1_1UI_1_1Api_1_1Helper_1_1RestHelper.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Reuser", "d2/d67/classFossology_1_1UI_1_1Api_1_1Models_1_1Reuser.html", null ],
    [ "Fossology\\Lib\\BusinessRules\\ReuseReportProcessor", "d4/d64/classFossology_1_1Lib_1_1BusinessRules_1_1ReuseReportProcessor.html", null ],
    [ "rpmpkginfo", "d4/d56/structrpmpkginfo.html", null ],
    [ "RunTest", "d4/d87/classRunTest.html", null ],
    [ "SanityChecker", "d8/d3c/classSanityChecker.html", null ],
    [ "Fossology\\UI\\Api\\Models\\Scancode", "db/d12/classFossology_1_1UI_1_1Api_1_1Models_1_1Scancode.html", null ],
    [ "Fossology\\Lib\\Proxy\\ScanJobProxy", "dc/d9e/classFossology_1_1Lib_1_1Proxy_1_1ScanJobProxy.html", null ],
    [ "Fossology\\UI\\Api\\Models\\ScannedLicense", "d3/d1b/classFossology_1_1UI_1_1Api_1_1Models_1_1ScannedLicense.html", null ],
    [ "scanner", "df/df2/classscanner.html", [
      [ "hCopyrightScanner", "dc/dd7/classhCopyrightScanner.html", null ],
      [ "regexScanner", "d2/db7/classregexScanner.html", null ]
    ] ],
    [ "FoScanner.Scanners.Scanners", "d6/d3d/classFoScanner_1_1Scanners_1_1Scanners.html", null ],
    [ "Fossology\\UI\\Api\\Models\\ScanOptions", "dd/d1f/classFossology_1_1UI_1_1Api_1_1Models_1_1ScanOptions.html", null ],
    [ "FoScanner.Scanners.ScanResult", "d7/d17/classFoScanner_1_1Scanners_1_1ScanResult.html", [
      [ "FoScanner.Scanners.ScanResultList", "d4/d6f/classFoScanner_1_1Scanners_1_1ScanResultList.html", null ]
    ] ],
    [ "scanResults", "d2/df5/structscanResults.html", null ],
    [ "scheduler_t", "d2/d3c/structscheduler__t.html", null ],
    [ "Fossology\\CliXml\\Test\\SchedulerTestRunner", "d5/da6/interfaceFossology_1_1CliXml_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\CliXml\\Test\\SchedulerTestRunnerCli", "d5/dbb/classFossology_1_1CliXml_1_1Test_1_1SchedulerTestRunnerCli.html", null ]
    ] ],
    [ "Fossology\\Compatibility\\Test\\SchedulerTestRunner", "d6/d18/interfaceFossology_1_1Compatibility_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\Compatibility\\Test\\SchedulerTestRunnerScheduler", "d4/dec/classFossology_1_1Compatibility_1_1Test_1_1SchedulerTestRunnerScheduler.html", null ]
    ] ],
    [ "Fossology\\Decider\\Test\\SchedulerTestRunner", "df/ded/interfaceFossology_1_1Decider_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\Decider\\Test\\SchedulerTestRunnerCli", "d0/d2d/classFossology_1_1Decider_1_1Test_1_1SchedulerTestRunnerCli.html", null ],
      [ "Fossology\\Decider\\Test\\SchedulerTestRunnerMock", "de/d00/classFossology_1_1Decider_1_1Test_1_1SchedulerTestRunnerMock.html", null ]
    ] ],
    [ "Fossology\\DeciderJob\\Test\\SchedulerTestRunner", "df/db5/interfaceFossology_1_1DeciderJob_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\DeciderJob\\Test\\SchedulerTestRunnerCli", "d4/d68/classFossology_1_1DeciderJob_1_1Test_1_1SchedulerTestRunnerCli.html", null ],
      [ "Fossology\\DeciderJob\\Test\\SchedulerTestRunnerMock", "d2/dc6/classFossology_1_1DeciderJob_1_1Test_1_1SchedulerTestRunnerMock.html", null ]
    ] ],
    [ "Fossology\\Ojo\\Test\\SchedulerTestRunner", "d0/db6/interfaceFossology_1_1Ojo_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\Ojo\\Test\\SchedulerTestRunnerScheduler", "da/d10/classFossology_1_1Ojo_1_1Test_1_1SchedulerTestRunnerScheduler.html", null ]
    ] ],
    [ "Fossology\\Report\\Test\\SchedulerTestRunner", "db/dd1/interfaceFossology_1_1Report_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\Report\\Test\\SchedulerTestRunnerCli", "de/d79/classFossology_1_1Report_1_1Test_1_1SchedulerTestRunnerCli.html", null ]
    ] ],
    [ "Fossology\\Reuser\\Test\\SchedulerTestRunner", "dd/df9/interfaceFossology_1_1Reuser_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\Reuser\\Test\\SchedulerTestRunnerCli", "d1/d1f/classFossology_1_1Reuser_1_1Test_1_1SchedulerTestRunnerCli.html", null ],
      [ "Fossology\\Reuser\\Test\\SchedulerTestRunnerMock", "d6/d44/classFossology_1_1Reuser_1_1Test_1_1SchedulerTestRunnerMock.html", null ]
    ] ],
    [ "Fossology\\Spdx\\Test\\SchedulerTestRunner", "df/d6e/interfaceFossology_1_1Spdx_1_1Test_1_1SchedulerTestRunner.html", [
      [ "Fossology\\Spdx\\Test\\SchedulerTestRunnerCli", "d8/d0b/classFossology_1_1Spdx_1_1Test_1_1SchedulerTestRunnerCli.html", null ]
    ] ],
    [ "Fossology\\Compatibility\\Test\\SchedulerTestRunnerCli", "d8/dee/classFossology_1_1Compatibility_1_1Test_1_1SchedulerTestRunnerCli.html", null ],
    [ "Fossology\\Ojo\\Test\\SchedulerTestRunnerCli", "d0/d87/classFossology_1_1Ojo_1_1Test_1_1SchedulerTestRunnerCli.html", null ],
    [ "Fossology\\Lib\\Dao\\SearchHelperDao", "da/d72/classFossology_1_1Lib_1_1Dao_1_1SearchHelperDao.html", null ],
    [ "Fossology\\UI\\Api\\Models\\SearchResult", "d4/de7/classFossology_1_1UI_1_1Api_1_1Models_1_1SearchResult.html", null ],
    [ "searchString", "d8/da8/structsearchString.html", null ],
    [ "SerializingMeta", "db/d5c/structSerializingMeta.html", null ],
    [ "Fossology\\UI\\Api\\Models\\ShowJob", "d5/da6/classFossology_1_1UI_1_1Api_1_1Models_1_1ShowJob.html", null ],
    [ "Fossology\\Lib\\Dao\\ShowJobsDao", "dd/dac/classFossology_1_1Lib_1_1Dao_1_1ShowJobsDao.html", null ],
    [ "SimpleReporter", null, [
      [ "JUnitXMLReporter", "de/d2f/classJUnitXMLReporter.html", null ]
    ] ],
    [ "SoftwareHeritage", "dc/d11/classSoftwareHeritage.html", null ],
    [ "SoftwareHeritageAgentPlugin", "d7/d3f/classSoftwareHeritageAgentPlugin.html", null ],
    [ "Fossology\\Lib\\Dao\\SoftwareHeritageDao", "d2/d1f/classFossology_1_1Lib_1_1Dao_1_1SoftwareHeritageDao.html", null ],
    [ "Fossology\\Lib\\Dao\\SpashtDao", "da/d25/classFossology_1_1Lib_1_1Dao_1_1SpashtDao.html", null ],
    [ "SpdxGeneratorUi", "d4/d1f/classSpdxGeneratorUi.html", null ],
    [ "Fossology\\Lib\\Data\\Report\\SpdxLicenseInfo", "da/d46/classFossology_1_1Lib_1_1Data_1_1Report_1_1SpdxLicenseInfo.html", null ],
    [ "FoScanner.SpdxReport.SpdxReport", "d0/daf/classFoScanner_1_1SpdxReport_1_1SpdxReport.html", null ],
    [ "spdxTest", "d6/dc0/classspdxTest.html", null ],
    [ "SpdxThreeAgentPlugin", "d1/dbe/classSpdxThreeAgentPlugin.html", null ],
    [ "Fossology\\Spdx\\SpdxUtils", "d0/d41/classFossology_1_1Spdx_1_1SpdxUtils.html", null ],
    [ "Fossology\\Lib\\Data\\SplitPosition", "df/d9b/classFossology_1_1Lib_1_1Data_1_1SplitPosition.html", null ],
    [ "sqlCopy_struct", "db/d33/structsqlCopy__struct.html", null ],
    [ "State", "d7/d97/classState.html", null ],
    [ "Fossology\\Lib\\Util\\StringOperation", "d0/d66/classFossology_1_1Lib_1_1Util_1_1StringOperation.html", null ],
    [ "Fossology\\UI\\Api\\Models\\SuccessfulAgent", "d6/d99/classFossology_1_1UI_1_1Api_1_1Models_1_1SuccessfulAgent.html", null ],
    [ "Fossology\\Lib\\Dao\\SysConfigDao", "d8/db4/classFossology_1_1Lib_1_1Dao_1_1SysConfigDao.html", null ],
    [ "test_common_cache", "dc/d63/classtest__common__cache.html", null ],
    [ "Fossology\\Lib\\Test\\TestAbstractDb", "d3/d27/classFossology_1_1Lib_1_1Test_1_1TestAbstractDb.html", [
      [ "Fossology\\Lib\\Test\\TestLiteDb", "d9/d36/classFossology_1_1Lib_1_1Test_1_1TestLiteDb.html", null ],
      [ "Fossology\\Lib\\Test\\TestPgDb", "d4/dcb/classFossology_1_1Lib_1_1Test_1_1TestPgDb.html", null ]
    ] ],
    [ "PHPUnit\\Framework\\TestCase", null, [
      [ "CommonCliTest", "de/dab/classCommonCliTest.html", [
        [ "NomosFunTest", "d7/d4c/classNomosFunTest.html", null ],
        [ "OneShotJSON", "dd/d21/classOneShotJSON.html", null ],
        [ "OneShotMultiFileTest", "d0/dca/classOneShotMultiFileTest.html", null ],
        [ "OneShotOracleBerkeleyDB", "da/da4/classOneShotOracleBerkeleyDB.html", null ],
        [ "OneShotafferoTest", "db/dd5/classOneShotafferoTest.html", null ],
        [ "OneShotbsdTest", "d2/dc6/classOneShotbsdTest.html", null ],
        [ "OneShotemptyTest", "d0/d1c/classOneShotemptyTest.html", null ],
        [ "OneShotgpl3Test", "d0/dd9/classOneShotgpl3Test.html", null ],
        [ "OneShotgplv21Test", "d8/d6f/classOneShotgplv21Test.html", null ],
        [ "OneShotnoneTest", "db/d00/classOneShotnoneTest.html", null ]
      ] ],
      [ "CompatibilityScheduledTest", "df/de6/classCompatibilityScheduledTest.html", null ],
      [ "Fossology\\CliXml\\Test\\SchedulerTest", "d2/d2f/classFossology_1_1CliXml_1_1Test_1_1SchedulerTest.html", null ],
      [ "Fossology\\Decider\\DeciderAgentTest", "d7/d70/classFossology_1_1Decider_1_1DeciderAgentTest.html", null ],
      [ "Fossology\\Decider\\Test\\SchedulerTest", "dc/d3f/classFossology_1_1Decider_1_1Test_1_1SchedulerTest.html", null ],
      [ "Fossology\\DeciderJob\\Test\\SchedulerTest", "d6/d41/classFossology_1_1DeciderJob_1_1Test_1_1SchedulerTest.html", null ],
      [ "Fossology\\Lib\\Application\\LicenseCsvExportTest", "da/dd4/classFossology_1_1Lib_1_1Application_1_1LicenseCsvExportTest.html", null ],
      [ "Fossology\\Lib\\Application\\LicenseCsvImportTest", "d6/dd5/classFossology_1_1Lib_1_1Application_1_1LicenseCsvImportTest.html", null ],
      [ "Fossology\\Lib\\Application\\RepositoryApiTest", "d4/d5c/classFossology_1_1Lib_1_1Application_1_1RepositoryApiTest.html", null ],
      [ "Fossology\\Lib\\Application\\UserInfoTest", "dd/d2c/classFossology_1_1Lib_1_1Application_1_1UserInfoTest.html", null ],
      [ "Fossology\\Lib\\BusinessRules\\AgentLicenseEventProcessorTest", "d6/d02/classFossology_1_1Lib_1_1BusinessRules_1_1AgentLicenseEventProcessorTest.html", null ],
      [ "Fossology\\Lib\\BusinessRules\\ClearingDecisionFilterTest", "df/de5/classFossology_1_1Lib_1_1BusinessRules_1_1ClearingDecisionFilterTest.html", null ],
      [ "Fossology\\Lib\\BusinessRules\\ClearingDecisionProcessorTest", "dc/dac/classFossology_1_1Lib_1_1BusinessRules_1_1ClearingDecisionProcessorTest.html", null ],
      [ "Fossology\\Lib\\BusinessRules\\ClearingEventProcessorTest", "da/d80/classFossology_1_1Lib_1_1BusinessRules_1_1ClearingEventProcessorTest.html", null ],
      [ "Fossology\\Lib\\BusinessRules\\LicenseMapTest", "d3/dce/classFossology_1_1Lib_1_1BusinessRules_1_1LicenseMapTest.html", null ],
      [ "Fossology\\Lib\\Dao\\AgentDaoTest", "d7/d54/classFossology_1_1Lib_1_1Dao_1_1AgentDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\ClearingDaoTest", "d5/dc2/classFossology_1_1Lib_1_1Dao_1_1ClearingDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\CopyrightDaoTest", "d0/da0/classFossology_1_1Lib_1_1Dao_1_1CopyrightDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\Data\\ItemTreeBoundsTest", "dd/d05/classFossology_1_1Lib_1_1Dao_1_1Data_1_1ItemTreeBoundsTest.html", null ],
      [ "Fossology\\Lib\\Dao\\FolderDaoTest", "dd/d52/classFossology_1_1Lib_1_1Dao_1_1FolderDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\LicenseDaoTest", "d4/d7e/classFossology_1_1Lib_1_1Dao_1_1LicenseDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\PfileDaoTest", "d1/d4b/classFossology_1_1Lib_1_1Dao_1_1PfileDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\ShowJobsDaoTest", "d5/d68/classFossology_1_1Lib_1_1Dao_1_1ShowJobsDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\TreeDaoTest", "d9/d11/classFossology_1_1Lib_1_1Dao_1_1TreeDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\UploadDaoTest", "db/d02/classFossology_1_1Lib_1_1Dao_1_1UploadDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\UploadPermissionDaoTest", "d5/d6d/classFossology_1_1Lib_1_1Dao_1_1UploadPermissionDaoTest.html", null ],
      [ "Fossology\\Lib\\Dao\\UserDaoTest", "d5/d2b/classFossology_1_1Lib_1_1Dao_1_1UserDaoTest.html", null ],
      [ "Fossology\\Lib\\Data\\AgentRefTest", "de/d4b/classFossology_1_1Lib_1_1Data_1_1AgentRefTest.html", null ],
      [ "Fossology\\Lib\\Data\\Clearing\\AgentClearingEventTest", "d9/d3c/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1AgentClearingEventTest.html", null ],
      [ "Fossology\\Lib\\Data\\Clearing\\ClearingEventTest", "de/db1/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingEventTest.html", null ],
      [ "Fossology\\Lib\\Data\\Clearing\\ClearingResultTest", "dd/d9c/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingResultTest.html", null ],
      [ "Fossology\\Lib\\Data\\ClearingDecisionBuilderTest", "d3/d3d/classFossology_1_1Lib_1_1Data_1_1ClearingDecisionBuilderTest.html", null ],
      [ "Fossology\\Lib\\Data\\Folder\\FolderTest", "dd/d17/classFossology_1_1Lib_1_1Data_1_1Folder_1_1FolderTest.html", null ],
      [ "Fossology\\Lib\\Data\\HighlightTest", "d1/dc2/classFossology_1_1Lib_1_1Data_1_1HighlightTest.html", null ],
      [ "Fossology\\Lib\\Data\\LicenseMatchTest", "df/da9/classFossology_1_1Lib_1_1Data_1_1LicenseMatchTest.html", null ],
      [ "Fossology\\Lib\\Data\\LicenseRefTest", "d9/df1/classFossology_1_1Lib_1_1Data_1_1LicenseRefTest.html", null ],
      [ "Fossology\\Lib\\Data\\LicenseTest", "d7/da3/classFossology_1_1Lib_1_1Data_1_1LicenseTest.html", null ],
      [ "Fossology\\Lib\\Data\\Package\\PackageTest", "d8/d4a/classFossology_1_1Lib_1_1Data_1_1Package_1_1PackageTest.html", null ],
      [ "Fossology\\Lib\\Data\\TextFragmentTest", "d2/d26/classFossology_1_1Lib_1_1Data_1_1TextFragmentTest.html", null ],
      [ "Fossology\\Lib\\Data\\Tree\\ItemTest", "d2/deb/classFossology_1_1Lib_1_1Data_1_1Tree_1_1ItemTest.html", null ],
      [ "Fossology\\Lib\\Data\\Upload\\UploadTest", "d8/df7/classFossology_1_1Lib_1_1Data_1_1Upload_1_1UploadTest.html", null ],
      [ "Fossology\\Lib\\Db\\DbManagerTest", "d1/d0d/classFossology_1_1Lib_1_1Db_1_1DbManagerTest.html", null ],
      [ "Fossology\\Lib\\Db\\DbManagerTestCase", "d8/d7d/classFossology_1_1Lib_1_1Db_1_1DbManagerTestCase.html", [
        [ "Fossology\\Lib\\Db\\ModernDbManagerTest", "d8/dfd/classFossology_1_1Lib_1_1Db_1_1ModernDbManagerTest.html", null ],
        [ "Fossology\\Lib\\Db\\SolidDbManagerTest", "df/dad/classFossology_1_1Lib_1_1Db_1_1SolidDbManagerTest.html", null ]
      ] ],
      [ "Fossology\\Lib\\Html\\LinkElementTest", "db/d0a/classFossology_1_1Lib_1_1Html_1_1LinkElementTest.html", null ],
      [ "Fossology\\Lib\\Html\\SimpleElementTest", "de/d25/classFossology_1_1Lib_1_1Html_1_1SimpleElementTest.html", null ],
      [ "Fossology\\Lib\\Plugin\\DefaultPluginTest", "dd/dbb/classFossology_1_1Lib_1_1Plugin_1_1DefaultPluginTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\DbViewProxyTest", "df/dc8/classFossology_1_1Lib_1_1Proxy_1_1DbViewProxyTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\LatestScannerProxyTest", "d3/d1f/classFossology_1_1Lib_1_1Proxy_1_1LatestScannerProxyTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\LicenseViewProxyTest", "df/d79/classFossology_1_1Lib_1_1Proxy_1_1LicenseViewProxyTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\ScanJobProxyTest", "d7/db1/classFossology_1_1Lib_1_1Proxy_1_1ScanJobProxyTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\UploadBrowseProxyTest", "d2/ddd/classFossology_1_1Lib_1_1Proxy_1_1UploadBrowseProxyTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\UploadTreeProxyTest", "dc/d7c/classFossology_1_1Lib_1_1Proxy_1_1UploadTreeProxyTest.html", null ],
      [ "Fossology\\Lib\\Proxy\\UploadTreeViewProxyTest", "d7/d9c/classFossology_1_1Lib_1_1Proxy_1_1UploadTreeViewProxyTest.html", null ],
      [ "Fossology\\Lib\\Report\\ClearedGetterCommonTest", "d6/d52/classFossology_1_1Lib_1_1Report_1_1ClearedGetterCommonTest.html", null ],
      [ "Fossology\\Lib\\Test\\EnumMapTestBase", "d0/d77/classFossology_1_1Lib_1_1Test_1_1EnumMapTestBase.html", [
        [ "Fossology\\Lib\\Data\\Clearing\\ClearingEventTypesTest", "df/d4d/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingEventTypesTest.html", null ],
        [ "Fossology\\Lib\\Data\\DecisionScopesTest", "d6/da3/classFossology_1_1Lib_1_1Data_1_1DecisionScopesTest.html", null ],
        [ "Fossology\\Lib\\Data\\DecisionTypesTest", "d6/d34/classFossology_1_1Lib_1_1Data_1_1DecisionTypesTest.html", null ]
      ] ],
      [ "Fossology\\Lib\\Test\\ReflectoryTest", "d9/d4e/classFossology_1_1Lib_1_1Test_1_1ReflectoryTest.html", null ],
      [ "Fossology\\Lib\\Test\\TestLiteDbTest", "d2/da9/classFossology_1_1Lib_1_1Test_1_1TestLiteDbTest.html", null ],
      [ "Fossology\\Lib\\Test\\TestPgDbTest", "de/dc7/classFossology_1_1Lib_1_1Test_1_1TestPgDbTest.html", null ],
      [ "Fossology\\Lib\\Text\\EncodingConverterTest", "d1/d74/classFossology_1_1Lib_1_1Text_1_1EncodingConverterTest.html", null ],
      [ "Fossology\\Lib\\UI\\FolderNavTest", "d9/dcd/classFossology_1_1Lib_1_1UI_1_1FolderNavTest.html", null ],
      [ "Fossology\\Lib\\Util\\ArrayOperationTest", "d8/d98/classFossology_1_1Lib_1_1Util_1_1ArrayOperationTest.html", null ],
      [ "Fossology\\Lib\\Util\\StringOperationTest", "d5/d2a/classFossology_1_1Lib_1_1Util_1_1StringOperationTest.html", null ],
      [ "Fossology\\Lib\\Util\\TimingLoggerTest", "d2/df6/classFossology_1_1Lib_1_1Util_1_1TimingLoggerTest.html", null ],
      [ "Fossology\\Lib\\View\\HighlightProcessorTest", "d5/d47/classFossology_1_1Lib_1_1View_1_1HighlightProcessorTest.html", null ],
      [ "Fossology\\Lib\\View\\HighlightRendererTest", "dc/d97/classFossology_1_1Lib_1_1View_1_1HighlightRendererTest.html", null ],
      [ "Fossology\\Lib\\View\\HighlightStateTest", "d3/d8b/classFossology_1_1Lib_1_1View_1_1HighlightStateTest.html", null ],
      [ "Fossology\\Lib\\View\\PagedHexResultTest", "da/d90/classFossology_1_1Lib_1_1View_1_1PagedHexResultTest.html", null ],
      [ "Fossology\\Lib\\View\\PagedResultTest", "de/d33/classFossology_1_1Lib_1_1View_1_1PagedResultTest.html", null ],
      [ "Fossology\\Lib\\View\\PagedTextResultTest", "d1/d7e/classFossology_1_1Lib_1_1View_1_1PagedTextResultTest.html", null ],
      [ "Fossology\\Lib\\View\\TextRendererTest", "da/dd1/classFossology_1_1Lib_1_1View_1_1TextRendererTest.html", null ],
      [ "Fossology\\Lib\\View\\UrlBuilderTest", "de/d80/classFossology_1_1Lib_1_1View_1_1UrlBuilderTest.html", null ],
      [ "Fossology\\Report\\Test\\SchedulerTest", "d3/dba/classFossology_1_1Report_1_1Test_1_1SchedulerTest.html", null ],
      [ "Fossology\\Reuser\\Test\\SchedulerTest", "df/db5/classFossology_1_1Reuser_1_1Test_1_1SchedulerTest.html", null ],
      [ "Fossology\\Spdx\\Test\\SchedulerTest", "d1/d20/classFossology_1_1Spdx_1_1Test_1_1SchedulerTest.html", null ],
      [ "Fossology\\Spdx\\spdxutilTest", "d9/df6/classFossology_1_1Spdx_1_1spdxutilTest.html", null ],
      [ "Fossology\\UI\\Api\\Helper\\RestHelperTest", "d2/dc2/classFossology_1_1UI_1_1Api_1_1Helper_1_1RestHelperTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\AuthControllerTest", "d3/dfc/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1AuthControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\CopyrightControllerTest", "d4/d73/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1CopyrightControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\FolderControllerTest", "d7/d4f/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1FolderControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\GroupControllerTest", "d4/d95/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1GroupControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\InfoControllerTest", "d5/df0/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1InfoControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\JobControllerTest", "dc/d61/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1JobControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\LicenseControllerTest", "d1/dc2/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1LicenseControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\MaintenanceControllerTest", "d3/df1/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1MaintenanceControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\ReportControllerTest", "d2/dda/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1ReportControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\UploadControllerTest", "dc/d78/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1UploadControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\UploadTreeControllerTest", "d1/d44/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1UploadTreeControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Controllers\\UserControllerTest", "dd/da8/classFossology_1_1UI_1_1Api_1_1Test_1_1Controllers_1_1UserControllerTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Helper\\AuthHelperTest", "df/dc8/classFossology_1_1UI_1_1Api_1_1Test_1_1Helper_1_1AuthHelperTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Helper\\DbHelperTest", "d9/d60/classFossology_1_1UI_1_1Api_1_1Test_1_1Helper_1_1DbHelperTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\AnalysisTest", "dc/d81/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1AnalysisTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\DeciderTest", "de/d53/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1DeciderTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\FileTest", "dd/da8/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1FileTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\FolderTest", "d8/d70/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1FolderTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\InfoTest", "dd/de9/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1InfoTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\LicenseTest", "d4/ddf/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1LicenseTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ReuserTest", "d3/d56/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ReuserTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ScanOptionsTest", "df/dcc/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ScanOptionsTest.html", null ],
      [ "MonkScheduledTest", "d6/df2/classMonkScheduledTest.html", null ],
      [ "NinkaScheduledTest", "d6/dc3/classNinkaScheduledTest.html", null ],
      [ "OjoScheduledTest", "dd/d38/classOjoScheduledTest.html", null ],
      [ "StartUpTest", "dd/d10/classStartUpTest.html", null ],
      [ "TestCLib", "d7/d7a/classTestCLib.html", null ],
      [ "bulkTest", "d3/d04/classbulkTest.html", null ],
      [ "cli1Test", "de/df5/classcli1Test.html", null ],
      [ "cliParamsTest4Mimetype", "d0/d42/classcliParamsTest4Mimetype.html", null ],
      [ "cliParamsTest4Ununpack", "d1/db6/classcliParamsTest4Ununpack.html", null ],
      [ "cliParamsTest4UnunpackExcption", "d9/d2e/classcliParamsTest4UnunpackExcption.html", null ],
      [ "cliParamsTest4Wget", "d9/da5/classcliParamsTest4Wget.html", null ],
      [ "cliTest", "da/d75/classcliTest.html", null ],
      [ "ft_DelagentTest", "d6/d5a/classft__DelagentTest.html", null ],
      [ "ft_cliDelagentTest", "d7/d64/classft__cliDelagentTest.html", null ],
      [ "ft_cliPkgagentTest", "d3/dbd/classft__cliPkgagentTest.html", null ],
      [ "schedulerTest", "de/d3c/classschedulerTest.html", null ],
      [ "test_common_active", "d4/d53/classtest__common__active.html", null ],
      [ "test_common_auth", "d5/d5d/classtest__common__auth.html", null ],
      [ "test_common_cached", "d2/df8/classtest__common__cached.html", null ],
      [ "test_common_cli", "d9/dd8/classtest__common__cli.html", null ],
      [ "test_common_dir", "db/d08/classtest__common__dir.html", null ],
      [ "test_common_license_file", "db/dec/classtest__common__license__file.html", null ],
      [ "test_common_parm", "de/d56/classtest__common__parm.html", null ],
      [ "test_common_pkg", "d2/d68/classtest__common__pkg.html", null ],
      [ "test_common_sysconfig", "d5/d76/classtest__common__sysconfig.html", null ],
      [ "test_common_ui", "db/df0/classtest__common__ui.html", null ],
      [ "test_cp2foss", "d2/d31/classtest__cp2foss.html", null ],
      [ "test_cp2foss", "d2/d31/classtest__cp2foss.html", null ],
      [ "test_cp2foss", "d2/d31/classtest__cp2foss.html", null ],
      [ "test_fo_copyright_list", "d0/d0a/classtest__fo__copyright__list.html", null ],
      [ "test_fo_nomos_license_list", "d4/d55/classtest__fo__nomos__license__list.html", null ],
      [ "test_fossdash_config", "d8/d52/classtest__fossdash__config.html", null ],
      [ "test_fossjobs", "d1/dda/classtest__fossjobs.html", null ],
      [ "test_oneshot", "d1/d21/classtest__oneshot.html", null ],
      [ "test_showjobs", "df/d92/classtest__showjobs.html", null ],
      [ "ui_picker_Test", "d0/da2/classui__picker__Test.html", null ]
    ] ],
    [ "TestDbFactory", "d6/d54/classTestDbFactory.html", null ],
    [ "CPPUNIT_NS ::TestFixture", null, [
      [ "regexConfProviderTestSuite", "dd/d5d/classregexConfProviderTestSuite.html", null ],
      [ "regexTest", "d1/dc1/classregexTest.html", null ],
      [ "regexTest", "d1/dc1/classregexTest.html", null ],
      [ "scannerTestSuite", "d6/d4c/classscannerTestSuite.html", null ],
      [ "scannerTestSuite", "d6/d4c/classscannerTestSuite.html", null ]
    ] ],
    [ "CPPUNIT_NS::TestFixture", null, [
      [ "FoLibCPPTest", "dc/d89/classFoLibCPPTest.html", null ],
      [ "NinkaWrapperTest", "da/ddd/classNinkaWrapperTest.html", null ],
      [ "TestCompatibility", "d7/d5f/classTestCompatibility.html", null ],
      [ "TestDataCheck", "dc/ddd/classTestDataCheck.html", null ],
      [ "TestUtility", "de/d67/classTestUtility.html", null ]
    ] ],
    [ "Fossology\\Lib\\Test\\TestInstaller", "d0/d39/classFossology_1_1Lib_1_1Test_1_1TestInstaller.html", null ],
    [ "TestReport", "d7/d4d/classTestReport.html", null ],
    [ "TestRun", "d2/d6a/classTestRun.html", null ],
    [ "Functional.testsuite", "d4/d23/classFunctional_1_1testsuite.html", null ],
    [ "TestSuite", null, [
      [ "GpClassTestSuite", "df/d2a/classGpClassTestSuite.html", null ],
      [ "groupFuncTests", "dd/dba/classgroupFuncTests.html", null ],
      [ "uploadsTest", "d8/d10/classuploadsTest.html", null ],
      [ "verifyUploadsTest", "dd/d0f/classverifyUploadsTest.html", null ]
    ] ],
    [ "Fossology\\Agent\\Copyright\\UI\\TextFindingsAjax", "de/d5e/classFossology_1_1Agent_1_1Copyright_1_1UI_1_1TextFindingsAjax.html", null ],
    [ "Fossology\\Lib\\Data\\TextFragment", "da/dc1/classFossology_1_1Lib_1_1Data_1_1TextFragment.html", null ],
    [ "Fossology\\Lib\\View\\TextRenderer", "d9/d6c/classFossology_1_1Lib_1_1View_1_1TextRenderer.html", null ],
    [ "timer", "d6/d88/classtimer.html", null ],
    [ "Fossology\\Lib\\Util\\TimingLogger", "d4/df6/classFossology_1_1Lib_1_1Util_1_1TimingLogger.html", [
      [ "Fossology\\Lib\\Util\\HackedTimingLogger", "d2/dcf/classFossology_1_1Lib_1_1Util_1_1HackedTimingLogger.html", null ]
    ] ],
    [ "Token", "df/dcd/structToken.html", null ],
    [ "Fossology\\UI\\Api\\Models\\TokenRequest", "d5/d13/classFossology_1_1UI_1_1Api_1_1Models_1_1TokenRequest.html", null ],
    [ "Fossology\\Lib\\Dao\\TreeDao", "dd/ddd/classFossology_1_1Lib_1_1Dao_1_1TreeDao.html", null ],
    [ "Fossology\\Lib\\Data\\Types", "d4/d12/classFossology_1_1Lib_1_1Data_1_1Types.html", [
      [ "Fossology\\Lib\\Data\\Clearing\\ClearingEventTypes", "d8/d64/classFossology_1_1Lib_1_1Data_1_1Clearing_1_1ClearingEventTypes.html", null ],
      [ "Fossology\\Lib\\Data\\DecisionScopes", "db/d89/classFossology_1_1Lib_1_1Data_1_1DecisionScopes.html", null ],
      [ "Fossology\\Lib\\Data\\DecisionTypes", "d5/db0/classFossology_1_1Lib_1_1Data_1_1DecisionTypes.html", null ],
      [ "Fossology\\Lib\\Data\\JobStatus", "d1/d08/classFossology_1_1Lib_1_1Data_1_1JobStatus.html", null ],
      [ "Fossology\\Lib\\Data\\UploadStatus", "d4/d28/classFossology_1_1Lib_1_1Data_1_1UploadStatus.html", null ]
    ] ],
    [ "ui_spashts", "d3/d24/classui__spashts.html", null ],
    [ "UnitTestCase", null, [
      [ "TestCLInputCP2foss", "d9/d50/classTestCLInputCP2foss.html", null ],
      [ "TestCLInputCP2foss", "d9/d50/classTestCLInputCP2foss.html", null ],
      [ "TestCP2fossRecursion", "d1/d6e/classTestCP2fossRecursion.html", null ],
      [ "TestDashD", "d0/d97/classTestDashD.html", null ],
      [ "TestDupFolders", "db/dcd/classTestDupFolders.html", null ]
    ] ],
    [ "unpackqueue", "d6/d06/structunpackqueue.html", null ],
    [ "Fossology\\Lib\\Data\\Upload\\Upload", "d4/dba/classFossology_1_1Lib_1_1Data_1_1Upload_1_1Upload.html", [
      [ "Fossology\\Lib\\Data\\Upload\\UploadProgress", "d3/da3/classFossology_1_1Lib_1_1Data_1_1Upload_1_1UploadProgress.html", null ]
    ] ],
    [ "Fossology\\UI\\Api\\Models\\Upload", "df/d8c/classFossology_1_1UI_1_1Api_1_1Models_1_1Upload.html", null ],
    [ "Fossology\\Lib\\Proxy\\UploadBrowseProxy", "d2/daf/classFossology_1_1Lib_1_1Proxy_1_1UploadBrowseProxy.html", null ],
    [ "Fossology\\Lib\\Dao\\UploadDao", "d3/daa/classFossology_1_1Lib_1_1Dao_1_1UploadDao.html", null ],
    [ "Fossology\\Lib\\Data\\Upload\\UploadEvents", "d1/d72/classFossology_1_1Lib_1_1Data_1_1Upload_1_1UploadEvents.html", null ],
    [ "Fossology\\UI\\Api\\Helper\\UploadHelper", "db/d4e/classFossology_1_1UI_1_1Api_1_1Helper_1_1UploadHelper.html", null ],
    [ "Fossology\\Lib\\Dao\\UploadPermissionDao", "d8/d4d/classFossology_1_1Lib_1_1Dao_1_1UploadPermissionDao.html", null ],
    [ "Fossology\\UI\\Api\\Models\\UploadSummary", "dc/d7f/classFossology_1_1UI_1_1Api_1_1Models_1_1UploadSummary.html", null ],
    [ "uploadtree", "d1/d1a/structuploadtree.html", null ],
    [ "uploadtree_struct", "d3/d1f/structuploadtree__struct.html", null ],
    [ "Fossology\\Lib\\View\\UrlBuilder", "d0/d7d/classFossology_1_1Lib_1_1View_1_1UrlBuilder.html", null ],
    [ "Fossology\\UI\\Api\\Models\\User", "dc/d9c/classFossology_1_1UI_1_1Api_1_1Models_1_1User.html", null ],
    [ "Fossology\\Lib\\Dao\\UserDao", "dd/d7d/classFossology_1_1Lib_1_1Dao_1_1UserDao.html", null ],
    [ "Fossology\\UI\\Api\\Models\\UserGroupMember", "de/d1d/classFossology_1_1UI_1_1Api_1_1Models_1_1UserGroupMember.html", null ],
    [ "Fossology\\UI\\Api\\Helper\\UserHelper", "db/d4b/classFossology_1_1UI_1_1Api_1_1Helper_1_1UserHelper.html", null ],
    [ "Fossology\\Lib\\Application\\UserInfo", "d1/d5d/classFossology_1_1Lib_1_1Application_1_1UserInfo.html", null ],
    [ "WebTestCase", null, [
      [ "TestAboutMenu", "df/ded/classTestAboutMenu.html", null ],
      [ "TestCreateFolder", "da/d0f/classTestCreateFolder.html", null ],
      [ "TestOrganizeFolders", "d1/dcd/classTestOrganizeFolders.html", null ],
      [ "TestRepoLogin", "df/d23/classTestRepoLogin.html", null ],
      [ "TestToolsMenu", "d9/d04/classTestToolsMenu.html", null ],
      [ "fossologyTest", "d5/dcd/classfossologyTest.html", [
        [ "fossologyTestCase", "d5/d51/classfossologyTestCase.html", [
          [ "AddUserTest", "de/d5c/classAddUserTest.html", null ],
          [ "BasicFolderTest", "d0/df5/classBasicFolderTest.html", null ],
          [ "CreateDeleteFldrTest", "d0/dac/classCreateDeleteFldrTest.html", null ],
          [ "CreateFolderTest", "df/d73/classCreateFolderTest.html", null ],
          [ "DeleteFolderTest", "db/d62/classDeleteFolderTest.html", null ],
          [ "DupFolderTest", "df/d0d/classDupFolderTest.html", null ],
          [ "DupUploadTest", "da/d6c/classDupUploadTest.html", null ],
          [ "DupUserTest", "d9/d9e/classDupUserTest.html", null ],
          [ "EditFolderDescriptionOnlyTest", "d0/d4a/classEditFolderDescriptionOnlyTest.html", null ],
          [ "EditFolderNameOnlyTest", "db/d8b/classEditFolderNameOnlyTest.html", null ],
          [ "EditFolderTest", "db/d5a/classEditFolderTest.html", null ],
          [ "EmailUserTest", "d5/d03/classEmailUserTest.html", null ],
          [ "FoldersCreateMenuTest", "d1/dfc/classFoldersCreateMenuTest.html", null ],
          [ "FoldersDeleteMenuTest", "d4/dcd/classFoldersDeleteMenuTest.html", null ],
          [ "FoldersEditMenuTest", "d0/dc8/classFoldersEditMenuTest.html", null ],
          [ "FoldersMoveMenuTest", "d0/def/classFoldersMoveMenuTest.html", null ],
          [ "MoveFolderTest", "da/dd5/classMoveFolderTest.html", null ],
          [ "MoveFolderTest", "da/dd5/classMoveFolderTest.html", null ],
          [ "OneShotTablegplv21Test", "d9/d33/classOneShotTablegplv21Test.html", null ],
          [ "OneShotgplv21Test", "d8/d6f/classOneShotgplv21Test.html", null ],
          [ "SearchMenuTest", "d1/d12/classSearchMenuTest.html", null ],
          [ "TestAboutMenu", "df/ded/classTestAboutMenu.html", null ],
          [ "TestRepoLogin", "df/d23/classTestRepoLogin.html", null ],
          [ "UploadFileMenuTest", "d9/d2f/classUploadFileMenuTest.html", null ],
          [ "UploadFileTest", "d7/dcb/classUploadFileTest.html", null ],
          [ "UploadInstructMenuTest", "d7/d2d/classUploadInstructMenuTest.html", null ],
          [ "UploadOneShotMenuTest", "df/d66/classUploadOneShotMenuTest.html", null ],
          [ "UploadServerMenuTest", "d4/dfd/classUploadServerMenuTest.html", null ],
          [ "UploadSrvTest", "d8/d6d/classUploadSrvTest.html", null ],
          [ "UploadUrlMenuTest", "db/d0b/classUploadUrlMenuTest.html", null ],
          [ "UploadUrlTest", "d2/d85/classUploadUrlTest.html", null ],
          [ "UploadsDeleteMenuTest", "d9/d26/classUploadsDeleteMenuTest.html", null ],
          [ "UploadsMoveMenuTest", "d2/d04/classUploadsMoveMenuTest.html", null ],
          [ "browseUPloadedTest", "dd/d8f/classbrowseUPloadedTest.html", null ],
          [ "cleanupRF", "d0/d7c/classcleanupRF.html", null ],
          [ "cleanupTestData", "dd/dc2/classcleanupTestData.html", null ],
          [ "createSuiUsers", "d0/da2/classcreateSuiUsers.html", null ],
          [ "createUIUsers", "db/dbe/classcreateUIUsers.html", null ],
          [ "myFirstTest", "da/d92/classmyFirstTest.html", null ],
          [ "noEmailUserTest", "d8/dbe/classnoEmailUserTest.html", null ],
          [ "rhelTest", "df/d44/classrhelTest.html", null ],
          [ "runMyTest", "d8/dff/classrunMyTest.html", null ],
          [ "someTest", "d5/d20/classsomeTest.html", null ],
          [ "uploadSrvDirTest", "d7/d44/classuploadSrvDirTest.html", null ],
          [ "uploadSrvFileTest", "d1/d90/classuploadSrvFileTest.html", null ],
          [ "uploadTestDataTest", "d2/dab/classuploadTestDataTest.html", null ],
          [ "uploadTestDataTest", "d2/dab/classuploadTestDataTest.html", null ],
          [ "uploadUnpack", "db/de2/classuploadUnpack.html", null ],
          [ "uploadWEMailTest", "db/d49/classuploadWEMailTest.html", null ],
          [ "uploadWoutEMailTest", "dc/dca/classuploadWoutEMailTest.html", null ],
          [ "userEditAnyTest", "d9/d10/classuserEditAnyTest.html", null ],
          [ "verify23D1F1L", "d2/dc1/classverify23D1F1L.html", null ],
          [ "verify23D1F1L", "d2/dc1/classverify23D1F1L.html", null ],
          [ "verify23D1F1L", "d2/dc1/classverify23D1F1L.html", null ],
          [ "verifyDirsOnly", "da/dc1/classverifyDirsOnly.html", null ],
          [ "verifyDirsOnly", "da/dc1/classverifyDirsOnly.html", null ],
          [ "verifyDirsOnly", "da/dc1/classverifyDirsOnly.html", null ],
          [ "verifyFossolyTest", "d6/ddc/classverifyFossolyTest.html", null ],
          [ "verifyFossolyTest", "d6/ddc/classverifyFossolyTest.html", null ],
          [ "verifyFossolyTest", "d6/ddc/classverifyFossolyTest.html", null ],
          [ "verifySimpletest", "d5/d2b/classverifySimpletest.html", null ],
          [ "verifySimpletest", "d5/d2b/classverifySimpletest.html", null ],
          [ "zendTest", "d2/d4e/classzendTest.html", null ]
        ] ]
      ] ]
    ] ],
    [ "AbstractExtension", null, [
      [ "Fossology\\Lib\\UI\\TwigExtensions\\TranslateFilter", "de/da1/classFossology_1_1Lib_1_1UI_1_1TwigExtensions_1_1TranslateFilter.html", null ]
    ] ],
    [ "Enum", null, [
      [ "FoScanner.ApiConfig.Runner", "db/df2/classFoScanner_1_1ApiConfig_1_1Runner.html", null ],
      [ "FoScanner.CliOptions.ReportFormat", "dc/d6c/classFoScanner_1_1CliOptions_1_1ReportFormat.html", null ]
    ] ],
    [ "Exception", null, [
      [ "Fossology\\Lib\\Exception", "d3/db8/classFossology_1_1Lib_1_1Exception.html", [
        [ "Fossology\\Lib\\Exceptions\\DuplicateTokenKeyException", "d8/d39/classFossology_1_1Lib_1_1Exceptions_1_1DuplicateTokenKeyException.html", null ],
        [ "Fossology\\Lib\\Exceptions\\DuplicateTokenNameException", "d3/dfe/classFossology_1_1Lib_1_1Exceptions_1_1DuplicateTokenNameException.html", null ],
        [ "Fossology\\Lib\\Exceptions\\HttpClientException", "d2/d72/classFossology_1_1Lib_1_1Exceptions_1_1HttpClientException.html", null ],
        [ "Fossology\\Lib\\Exceptions\\InvalidAgentStageException", "d7/da2/classFossology_1_1Lib_1_1Exceptions_1_1InvalidAgentStageException.html", null ]
      ] ],
      [ "Fossology\\UI\\Api\\Exceptions\\HttpErrorException", "d6/d7b/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpErrorException.html", [
        [ "Fossology\\UI\\Api\\Exceptions\\HttpBadRequestException", "d2/d70/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpBadRequestException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpConflictException", "db/dff/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpConflictException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpForbiddenException", "dc/dd8/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpForbiddenException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpInternalServerErrorException", "de/d8c/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpInternalServerErrorException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpNotFoundException", "dd/dfb/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpNotFoundException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpPreconditionFailException", "d7/d9c/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpPreconditionFailException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpServiceUnavailableException", "da/dbb/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpServiceUnavailableException.html", null ],
        [ "Fossology\\UI\\Api\\Exceptions\\HttpTooManyRequestException", "d0/d11/classFossology_1_1UI_1_1Api_1_1Exceptions_1_1HttpTooManyRequestException.html", null ]
      ] ],
      [ "Functional.DefineError", "d7/d5a/classFunctional_1_1DefineError.html", null ],
      [ "Functional.TimeoutError", "d8/ddb/classFunctional_1_1TimeoutError.html", null ]
    ] ],
    [ "Response", null, [
      [ "Fossology\\UI\\Api\\Helper\\ResponseHelper", "d7/d48/classFossology_1_1UI_1_1Api_1_1Helper_1_1ResponseHelper.html", null ]
    ] ],
    [ "ResponseFactory", null, [
      [ "Fossology\\UI\\Api\\Helper\\ResponseFactoryHelper", "d2/ddf/classFossology_1_1UI_1_1Api_1_1Helper_1_1ResponseFactoryHelper.html", null ]
    ] ],
    [ "TestCase", null, [
      [ "Fossology\\Lib\\Dao\\LicenseStdCommentDaoTest", "d8/dd3/classFossology_1_1Lib_1_1Dao_1_1LicenseStdCommentDaoTest.html", null ],
      [ "Fossology\\Tests\\CommonMenuTest", "da/daa/classFossology_1_1Tests_1_1CommonMenuTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\AdminAcknowledgementTest", "db/d2f/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1AdminAcknowledgementTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\AgentTest", "df/db3/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1AgentTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ApiVersionTest", "d9/dac/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ApiVersionTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\BulkHistoryTest", "d8/d35/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1BulkHistoryTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ClearingHistoryTest", "d2/de2/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ClearingHistoryTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ConfTest", "df/dce/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ConfTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\EditedLicenseTest", "d0/d8b/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1EditedLicenseTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\FileInfoTest", "da/d32/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1FileInfoTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\FileLicensesTest", "d8/d9b/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1FileLicensesTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\FindingsTest", "da/dfa/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1FindingsTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\GroupPermissionsTest", "d9/d18/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1GroupPermissionsTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\GroupTest", "d2/dfb/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1GroupTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\HashTest", "d4/d2f/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1HashTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\JobQueueTest", "d2/d98/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1JobQueueTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\JobTest", "d5/d1b/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1JobTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\LicenseCandidateTest", "d3/d92/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1LicenseCandidateTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\LicenseDecisionTest", "de/d08/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1LicenseDecisionTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\LicenseStandardCommentTest", "de/d7e/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1LicenseStandardCommentTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ObligationTest", "d9/db6/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ObligationTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\OneShotTest", "d8/dda/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1OneShotTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\PermissionsTest", "d5/d20/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1PermissionsTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ScanCodeTest", "dc/d61/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ScanCodeTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ScannedLicenseTest", "d9/dc9/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ScannedLicenseTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\SearchResultTest", "de/d15/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1SearchResultTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\ShowJobTest", "d5/d7c/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1ShowJobTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\SuccessfulAgentTest", "d1/daa/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1SuccessfulAgentTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\TokenRequestTest", "d9/d57/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1TokenRequestTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\UploadSummaryTest", "d7/d44/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1UploadSummaryTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\UploadTest", "dc/d39/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1UploadTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\UserGroupMemberTest", "d1/dd6/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1UserGroupMemberTest.html", null ],
      [ "Fossology\\UI\\Api\\Test\\Models\\UserTest", "da/d8c/classFossology_1_1UI_1_1Api_1_1Test_1_1Models_1_1UserTest.html", null ]
    ] ]
];